### ISSUE TITLE
Too many open files after some times to use the print server

### ISSUE THREAD

**Issue by sbrunner** [mapfish/mapfish-print#143]
After some times to use the print we have the error:

```
2014-08-22 13:42:42,668 [http-8080-Acceptor-0] ERROR he.tomcat.util.net.JIoEndpoint - Socket accept failed
java.net.SocketException: Too many open files
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:408)
        at java.net.ServerSocket.implAccept(ServerSocket.java:462)
        at java.net.ServerSocket.accept(ServerSocket.java:430)
        at org.apache.tomcat.util.net.DefaultServerSocketFactory.acceptSocket(DefaultServerSocketFactory.java:61)
        at org.apache.tomcat.util.net.JIoEndpoint$Acceptor.run(JIoEndpoint.java:352)
        at java.lang.Thread.run(Thread.java:662)
```

An other exception who aspires on restart:

```
2014-08-22 15:50:53,476 [main] ERROR st].[/print-c2cgeoportal-main] - Exception sending context destroyed event to listener instance of class org.springframework.web.context.ContextLoaderListener
java.lang.NoClassDefFoundError: org/springframework/web/context/ContextCleanupListener
        at org.springframework.web.context.ContextLoaderListener.contextDestroyed(ContextLoaderListener.java:144)
        at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4245)
        at org.apache.catalina.core.StandardContext.stop(StandardContext.java:4886)
        at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:936)
        at org.apache.catalina.startup.HostConfig.undeployApps(HostConfig.java:1359)
        at org.apache.catalina.startup.HostConfig.stop(HostConfig.java:1330)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:326)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:142)
        at org.apache.catalina.core.ContainerBase.stop(ContainerBase.java:1098)
        at org.apache.catalina.core.ContainerBase.stop(ContainerBase.java:1110)
        at org.apache.catalina.core.StandardEngine.stop(StandardEngine.java:468)
        at org.apache.catalina.core.StandardService.stop(StandardService.java:604)
        at org.apache.catalina.core.StandardServer.stop(StandardServer.java:788)
        at org.apache.catalina.startup.Catalina.stop(Catalina.java:662)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:629)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)
Caused by: java.lang.ClassNotFoundException: org.springframework.web.context.ContextCleanupListener
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1680)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1526)
        ... 21 more
2014-08-22 15:50:53,487 [main] WARN  he.catalina.startup.HostConfig - Error while removing context [/print-c2cgeoportal-main]
java.lang.NullPointerException
        at org.apache.catalina.loader.WebappClassLoader.findResourceInternal(WebappClassLoader.java:2963)
        at org.apache.catalina.loader.WebappClassLoader.findResource(WebappClassLoader.java:1242)
        at org.apache.catalina.loader.WebappClassLoader.getResourceAsStream(WebappClassLoader.java:1475)
        at org.apache.catalina.loader.WebappClassLoader.clearReferencesJdbc(WebappClassLoader.java:1972)
        at org.apache.catalina.loader.WebappClassLoader.clearReferences(WebappClassLoader.java:1915)
        at org.apache.catalina.loader.WebappClassLoader.stop(WebappClassLoader.java:1833)
        at org.apache.catalina.loader.WebappLoader.stop(WebappLoader.java:740)
        at org.apache.catalina.core.StandardContext.stop(StandardContext.java:4920)
        at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:936)
        at org.apache.catalina.startup.HostConfig.undeployApps(HostConfig.java:1359)
        at org.apache.catalina.startup.HostConfig.stop(HostConfig.java:1330)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:326)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:142)
        at org.apache.catalina.core.ContainerBase.stop(ContainerBase.java:1098)
        at org.apache.catalina.core.ContainerBase.stop(ContainerBase.java:1110)
        at org.apache.catalina.core.StandardEngine.stop(StandardEngine.java:468)
        at org.apache.catalina.core.StandardService.stop(StandardService.java:604)
        at org.apache.catalina.core.StandardServer.stop(StandardServer.java:788)
        at org.apache.catalina.startup.Catalina.stop(Catalina.java:662)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:629)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)
```

And we have the message

```
2014-08-25 14:23:38,640 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] ERROR alina.loader.WebappClassLoader - The web application [/print-c2cgeoportal-main] created a ThreadLocal with key of type [com.codahale.metrics.ThreadLocalRandom$1] (value [com.codahale.metrics.ThreadLocalRandom$1@786bb78a]) and a value of type [com.codahale.metrics.ThreadLocalRandom] (value [com.codahale.metrics.ThreadLocalRandom@67df02c9]) but failed to remove it when the web application was stopped. This is very likely to create a memory leak.
```

**Comment by teddmason** [comment]
Was this issue ever fixed? I'm guessing as it is still open after all this time that it was never fixed in V2 of mapfish

**Comment by tixvieira** [comment]
We had the same problem, and we've made some modifications to close the PDFReader that leave those opened connections.
I would like to push the code to a 2.1.3 version.
Can i do it into the branch 2.1.x?

There is anyone still maintaining v2, and do the releases?

Thanks

Tiago

**Comment by pvalsecc** [comment]
@tixvieira, you can always do a PR. But as far I can tell, v2 is not maintained anymore. I wouldn't know how to do a release. Maybe @sbrunner?

**Comment by tixvieira** [comment]
@pvalsecc , PR created: https://github.com/mapfish/mapfish-print/pull/739
Someone can review and do a 2.1.3 release? Thanks

**Comment by tixvieira** [comment]
@sbrunner, are you able to do 2.1.3 release? Thanks

**Comment by tixvieira** [comment]
@pvalsecc , can you try to release this 2.1.3 version?

README indicates:
== Deploy ==
The following command will build and upload all artifacts to the dev.mapfish.org repository.
  > ./gradlew upload -DsshPassphrase=...

I would like to upgrade geoserver to that released version.

Thanks

**Comment by tixvieira** [comment]
@pvalsecc, the release is already in mvnrepository.
It works fine. You can close this issue.

Now i will open a new PR on Geoserver to update it.
https://osgeo-org.atlassian.net/browse/GEOS-8968

Thank you :)
