### ISSUE TITLE
Find the version corresponding to Jasper Version

### ISSUE THREAD

**Issue by svareg** [mapfish/mapfish-print#1482]
Hello,

We've just migrated to JasperSoft-Desktop version 6.11.0.
It seem that the Version of MapFishPrint we are currently using (3.18.2) is not compatible with this version, because when we make changes in our print-templates using Jasper-Desktop, MFP 3.18.2 cannot work with them anymore.

How can I find to which Version of MFP we should migrate to, in order to stay compatible with our Jasper Version?

Thanks for the information,
Regards,
Guillaume.

**Comment by sbrunner** [comment]
For the version 3.24.0, here: https://github.com/mapfish/mapfish-print/blob/release/3.24.0/build.gradle#L30 :-)

**Comment by svahul** [comment]
Hi,

We have tried to migrated to version 3.25.0. 
The provided _print-servlet-3.25.0.war_ has a problem in the _manifest.mf_.
When include the File on our server, the following error appears:

```
20-Oct-2020 14:07:41.890 WARNING [localhost-startStop-2] org.apache.catalina.webresources.DirResourceSet.initInternal Failed to read manifest from [/usr/local/tomcat/webapps/test/META-INF/MANIFEST.MF]
        java.io.IOException: invalid manifest format
                at java.util.jar.Manifest.read(Manifest.java:260)
                at java.util.jar.Manifest.<init>(Manifest.java:81)
                at java.util.jar.Manifest.<init>(Manifest.java:73)
                at org.apache.catalina.webresources.DirResourceSet.initInternal(DirResourceSet.java:272)
                at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:173)
                at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:714)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4816)
                at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4951)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
                at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
                at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
                at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
                at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1841)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)
20-Oct-2020 14:07:42.022 SEVERE [localhost-startStop-2] org.apache.catalina.core.StandardContext.startInternal Error while attempting to validate required application extensions
        java.io.IOException: invalid manifest format
                at java.util.jar.Manifest.read(Manifest.java:260)
                at java.util.jar.Manifest.<init>(Manifest.java:81)
                at java.util.jar.Manifest.<init>(Manifest.java:73)
                at org.apache.catalina.util.ExtensionValidator.validateApplication(ExtensionValidator.java:137)
                at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4971)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
                at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
                at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
                at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
                at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1841)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)
20-Oct-2020 14:07:42.023 SEVERE [localhost-startStop-2] org.apache.catalina.core.StandardContext.startInternal One or more components marked the context as not correctly configured
```

How can this error be solved?

Thank you and greetings
Loris

**Comment by sbrunner** [comment]
I don't know, currently I only use the Docker version of the print, sorry...

**Comment by jwkaltz** [comment]
It seems the WAR package of MapFish Print is broken. We are starting investigating this in another context (namely, using MapFish Print for https://github.com/openoereb/pyramid_oereb_mfp).

Just to be sure @svahul , you are not using MapFish Print in Docker?

**Comment by svahul** [comment]
@jwkaltz : We are not using Docker for MapFish Print

**Comment by jwkaltz** [comment]
@svahul here is the quick fix reported by another user (François from sitn) regarding the usage of the war archive:

There is an empty line in the Manifest file between Git-Revision and Build-By, that Tomcat does not like. Once this line removed, the error disappears.

**Comment by sbrunner** [comment]
=> duplicated of #1540

**Comment by svahul** [comment]
Thanks for the input. With the correction of the manifest file i got further. But then i get another error:

```
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: 15:25:06.014 [localhost-startStop-1] INFO  o.s.web.context.ContextLoader - Root WebApplicationContext: initialization started
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: 15:25:06.081 [localhost-startStop-1] DEBUG o.s.w.c.s.XmlWebApplicationContext - Refreshing Root WebApplicationContext
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: 15:25:06.170 [localhost-startStop-1] DEBUG o.s.b.f.xml.XmlBeanDefinitionReader - Loaded 1 bean definitions from URL [file:/usr/local/tomcat/webapps/svahul/WEB-INF/classes/mapfish-spring-custom-fonts.xml]
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: 15:25:06.178 [localhost-startStop-1] DEBUG o.s.b.f.xml.XmlBeanDefinitionReader - Loaded 12 bean definitions from URL [file:/usr/local/tomcat/webapps/svahul/WEB-INF/classes/mapfish-spring-config-objects.xml]
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: 15:25:06.184 [localhost-startStop-1] DEBUG o.s.b.f.xml.XmlBeanDefinitionReader - Loaded 18 bean definitions from URL [file:/usr/local/tomcat/webapps/svahul/WEB-INF/classes/mapfish-spring-attributes.xml]
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: 15:25:06.201 [localhost-startStop-1] DEBUG o.s.b.f.xml.XmlBeanDefinitionReader - Loaded 44 bean definitions from URL [file:/usr/local/tomcat/webapps/svahul/WEB-INF/classes/mapfish-spring-processors.xml]
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: 15:25:06.207 [localhost-startStop-1] DEBUG o.s.b.f.xml.XmlBeanDefinitionReader - Loaded 11 bean definitions from URL [file:/usr/local/tomcat/webapps/svahul/WEB-INF/classes/mapfish-spring-layer-parser.xml]
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: 15:25:06.216 [localhost-startStop-1] DEBUG o.s.b.f.xml.XmlBeanDefinitionReader - Loaded 2 bean definitions from URL [file:/usr/local/tomcat/webapps/svahul/WEB-INF/classes/mapfish-spring-style-parsers.xml]
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: 15:25:06.222 [localhost-startStop-1] DEBUG o.s.b.f.xml.XmlBeanDefinitionReader - Loaded 4 bean definitions from URL [file:/usr/local/tomcat/webapps/svahul/WEB-INF/classes/mapfish-spring-config-file-loaders.xml]
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: 15:25:06.235 [localhost-startStop-1] DEBUG o.s.b.f.xml.XmlBeanDefinitionReader - Loaded 13 bean definitions from URL [file:/usr/local/tomcat/webapps/svahul/WEB-INF/classes/mapfish-spring-config-output-formats.xml]
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: 15:25:06.238 [localhost-startStop-1] DEBUG o.s.b.f.xml.XmlBeanDefinitionReader - Loaded 4 bean definitions from URL [file:/usr/local/tomcat/webapps/svahul/WEB-INF/classes/mapfish-spring-access-assertions.xml]
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: 15:25:06.244 [localhost-startStop-1] DEBUG o.s.b.f.xml.XmlBeanDefinitionReader - Loaded 0 bean definitions from URL [file:/usr/local/tomcat/webapps/svahul/WEB-INF/classes/mapfish-spring-named-styles.xml]
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: 15:25:06.269 [localhost-startStop-1] DEBUG o.s.b.f.xml.XmlBeanDefinitionReader - Loaded 8 bean definitions from URL [file:/usr/local/tomcat/webapps/svahul/WEB-INF/classes/mapfish-spring-hibernate.xml]
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: 15:25:06.294 [localhost-startStop-1] DEBUG o.s.b.f.xml.XmlBeanDefinitionReader - Loaded 149 bean definitions from URL [file:/usr/local/tomcat/webapps/svahul/WEB-INF/classes/mapfish-spring-application-context.xml]
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: 15:25:06.321 [localhost-startStop-1] INFO  o.s.s.core.SpringSecurityCoreVersion - You are running with Spring Security Core 5.1.3.RELEASE
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: 15:25:06.327 [localhost-startStop-1] INFO  o.s.s.c.SecurityNamespaceHandler - Spring Security 'config' module version is 5.1.3.RELEASE
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: 15:25:06.372 [localhost-startStop-1] INFO  o.s.s.c.h.FilterInvocationSecurityMetadataSourceParser - Creating access control expression attribute 'isAuthenticated()' for /sec/print/**
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: 15:25:06.374 [localhost-startStop-1] INFO  o.s.s.c.h.FilterInvocationSecurityMetadataSourceParser - Creating access control expression attribute 'permitAll()' for /**
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: 15:25:06.396 [localhost-startStop-1] INFO  o.s.s.c.h.HttpSecurityBeanDefinitionParser - Checking sorted filter chain: [Root bean: class [org.springframework.security.web.access.channel.ChannelProcessingFilter]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 100, Root bean: class [org.springframework.security.web.context.SecurityContextPersistenceFilter]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 200, Root bean: class [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 400, Root bean: class [org.springframework.security.web.header.HeaderWriterFilter]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 500, Root bean: class [org.springframework.security.web.authentication.www.BasicAuthenticationFilter]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 1800, Root bean: class [org.springframework.security.web.savedrequest.RequestCacheAwareFilter]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 1900, Root bean: class [null]; scope=; abstract=false; lazyInit=null;
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.security.config.http.HttpConfigurationBuilder$SecurityContextHolderAwareRequestFilterBeanFactory#0; factoryMethodName=getBean; initMethodName=null; destroyMethodName=null, order = 2000, Root bean: class [org.springframework.security.web.authentication.AnonymousAuthenticationFilter]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 2300, Root bean: class [org.springframework.security.web.session.SessionManagementFilter]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 2400, Root bean: class [org.springframework.security.web.access.ExceptionTranslationFilter]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 2500, <org.springframework.security.web.access.intercept.FilterSecurityInterceptor#0>, order = 2600]
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: 15:25:06.402 [localhost-startStop-1] DEBUG o.s.b.f.xml.XmlBeanDefinitionReader - Loaded 22 bean definitions from class path resource [mapfish-spring-security.xml]
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: 15:25:06.410 [localhost-startStop-1] DEBUG o.s.b.f.xml.XmlBeanDefinitionReader - Loaded 1 bean definitions from ServletContext resource [/WEB-INF/mapfish-print-printer-factory.xml]
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: 15:25:06.415 [localhost-startStop-1] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Overriding bean definition for bean 'jobManager' with a different definition: replacing [Generic bean: class [org.mapfish.print.servlet.job.impl.ThreadPoolJobManager]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in URL [file:/usr/local/tomcat/webapps/svahul/WEB-INF/classes/mapfish-spring-application-context.xml]] with [Generic bean: class [org.mapfish.print.servlet.job.impl.ThreadPoolJobManager]; scope=; abstract=false; lazyInit=true; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in URL [file:/usr/local/tomcat/webapps/svahul/WEB-INF/classes/mapfish-spring-application-context-override.xml]]
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: 15:25:06.416 [localhost-startStop-1] DEBUG o.s.b.f.xml.XmlBeanDefinitionReader - Loaded 0 bean definitions from URL [file:/usr/local/tomcat/webapps/svahul/WEB-INF/classes/mapfish-spring-application-context-override.xml]
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: 15:25:06.526 [localhost-startStop-1] ERROR o.s.web.context.ContextLoader - Context initialization failed
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]: java.lang.NoSuchMethodError: org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(Ljava/lang/Class;Lorg/springframework/util/ReflectionUtils$MethodFilter;)[Ljava/lang/reflect/Method;
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$getTypeForFactoryMethod$2(AbstractAutowireCapableBeanFactory.java:743)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:742)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:681)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:649)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1604)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:520)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:491)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:86)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:400)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:291)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4701)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5167)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1125)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1859)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Oct 28 16:25:06 bvdgdi-svdprt2 docker-tomcat[63540]:         at java.lang.Thread.run(Thread.java:748)
```

Do you have an idea where that comes from?
