### ISSUE TITLE
Invalid Manifest Format when processing .war by Tomcat

### ISSUE THREAD

**Issue by RussellGrew** [mapfish/mapfish-print#1540]
**Context**

- MapFish print version: 3.26, 3.25, 3.24.2 .war file from github release
- Java version: OpenJDK 11
- Tomcat 8.5 64 bit
- OS: Windows 10

**Describe the bug**

After copying the war file into `webapps` the processing fails.

```
26-Oct-2020 15:19:50.490 INFO [localhost-startStop-2] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\print-servlet-3.26.0.war]
26-Oct-2020 15:19:52.879 WARNING [localhost-startStop-2] org.apache.catalina.webresources.DirResourceSet.initInternal Failed to read manifest from [C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\print-servlet-3.26.0\META-INF\MANIFEST.MF]
	java.io.IOException: invalid manifest format
		at java.base/java.util.jar.Manifest.read(Manifest.java:257)
		at java.base/java.util.jar.Manifest.<init>(Manifest.java:80)
		at java.base/java.util.jar.Manifest.<init>(Manifest.java:72)
		at org.apache.catalina.webresources.DirResourceSet.initInternal(DirResourceSet.java:272)
		at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:173)
		at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:714)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4816)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4951)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1841)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base/java.lang.Thread.run(Thread.java:834)
26-Oct-2020 15:20:02.188 SEVERE [localhost-startStop-2] org.apache.catalina.core.StandardContext.startInternal Error while attempting to validate required application extensions
	java.io.IOException: invalid manifest format

```

**How to reproduce**

Copy the war file into webapps.

**Expected results**

I expected the war file to work.

The MANIFEST.MF contains

```
Manifest-Version: 1.0
Build-Java-Runtime-Name: OpenJDK Runtime Environment
Build-OS-Name: Linux
Mapfish-Print-Version: 3.24.2
Build-Time: 10/21/20 10:03:24 AM
Build-OS-Arch: amd64
Git-Revision: 90dea2966b0c4b746078bf80848576e13769d0f9

Build-By: runner
Build-Java-Version: 1.8.0_265


```

I tested a GeoServer .war, which is the only other package I am familiar with, and it installs fine.

Thanks.

**Comment by teofilosalgado** [comment]
Same problem here. Tested with:
-     MapFish print version: 3.26 .war file from github release
-     Java version: Oracle JDK 11
-     Tomcat version: 9.0.41 64 bit
-     OS: Windows 10

**Comment by sbrunner** [comment]
And it's working with version 3.25?

**Comment by teofilosalgado** [comment]
@sbrunner sadly, no. Same manifest error as latest version:
```
08-Jan-2021 08:06:28.691 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardContext.startInternal Error while attempting to validate required application extensions
        java.io.IOException: invalid manifest format
                at java.base/java.util.jar.Manifest.read(Manifest.java:257)
                at java.base/java.util.jar.Manifest.<init>(Manifest.java:80)
                at java.base/java.util.jar.Manifest.<init>(Manifest.java:72)
```

**Comment by jwkaltz** [comment]
As a quick fix, you can unzip the war, remove the empty line in /var/lib/tomcat9/webapps/mapfish/META-INF/MANIFEST.MF, and rezip the war

(see also here: https://github.com/mapfish/mapfish-print/issues/1545#issue-731163197)

**Comment by teofilosalgado** [comment]
@jwkaltz Thank you! Removing the empty lines allowed the deploy to proceed! I just needed to add a `print-apps` (according to [this](https://gis.stackexchange.com/questions/325136/installing-mapfish)) folder inside the depployed `.war` folder.
