### ISSUE TITLE
buildreport route seem to be brocken ?

### ISSUE THREAD

**Issue by sbrunner** [mapfish/mapfish-print#165]
```
17:14:31.366 [PrintJobManager-6] INFO  o.mapfish.print.servlet.job.PrintJob - Error executing print job a86c92fa-299a-4823-98c3-e487d906665d@ba49e669-0c0b-463f-b8eb-83fb0df487b9
spec:
        {"app":"default","outputFormat":"pdf","layout":"A4 portrait","attributes":{"requestHeaders":{"requestHeaders":{"content-type":["application/json"],"host":["dpfe.org"],"content-length":["419"],"accept":["*/*"],"user-agent":["curl/7.26.0"]}},"map":{"center":[600000,200000],"scale":1000000,"rotation":0,"layers":[],"projection":"EPSG:21781","dpi":72}}}
java.lang.IllegalStateException: Target host is null
        at org.apache.http.util.Asserts.notNull(Asserts.java:46) ~[httpcore-4.3.2.jar:4.3.2]
        at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125) ~[httpclient-4.3.3.jar:4.3.3]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.3.3.jar:4.3.3]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.3.3.jar:4.3.3]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57) ~[httpclient-4.3.3.jar:4.3.3]
        at org.mapfish.print.http.MfClientHttpRequestFactoryImpl$Request.executeInternal(MfClientHttpRequestFactoryImpl.java:169) ~[MfClientHttpRequestFactoryImpl$Request.class:na]
        at org.mapfish.print.http.MfClientHttpRequestFactoryImpl$Request.executeInternal(MfClientHttpRequestFactoryImpl.java:100) ~[MfClientHttpRequestFactoryImpl$Request.class:na]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:49) ~[spring-web-3.2.8.RELEASE.jar:3.2.8.RELEASE]
        at org.mapfish.print.http.ConfigFileResolvingHttpRequestFactory$ConfigFileResolvingRequest.executeCallbacksAndRequest(ConfigFileResolvingHttpRequestFactory.java:136) ~[ConfigFileResolvingHttpRequestFactory$ConfigFileResolvingRequest.class:na]
        at org.mapfish.print.http.ConfigFileResolvingHttpRequestFactory$ConfigFileResolvingRequest.executeInternal(ConfigFileResolvingHttpRequestFactory.java:128) ~[ConfigFileResolvingHttpRequestFactory$ConfigFileResolvingRequest.class:na]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:49) ~[spring-web-3.2.8.RELEASE.jar:3.2.8.RELEASE]
        at org.mapfish.print.output.MapfishPrintRepositoryService.getInputStream(MapfishPrintRepositoryService.java:81) ~[MapfishPrintRepositoryService.class:na]
        at org.mapfish.print.output.MapfishPrintRepositoryService.getResource(MapfishPrintRepositoryService.java:102) ~[MapfishPrintRepositoryService.class:na]
        at net.sf.jasperreports.repo.RepositoryUtil.findInputStream(RepositoryUtil.java:304) ~[jasperreports-5.5.0.jar:5.5.0]
        at net.sf.jasperreports.repo.RepositoryUtil.getBytesFromLocation(RepositoryUtil.java:320) ~[jasperreports-5.5.0.jar:5.5.0]
        at net.sf.jasperreports.engine.RenderableUtil.getRenderable(RenderableUtil.java:121) ~[jasperreports-5.5.0.jar:5.5.0]
        at net.sf.jasperreports.engine.fill.JRFillImage.evaluateImage(JRFillImage.java:536) ~[jasperreports-5.5.0.jar:5.5.0]
        at net.sf.jasperreports.engine.fill.JRFillImage.evaluate(JRFillImage.java:472) ~[jasperreports-5.5.0.jar:5.5.0]
        at net.sf.jasperreports.engine.fill.JRFillElementContainer.evaluate(JRFillElementContainer.java:259) ~[jasperreports-5.5.0.jar:5.5.0]
        at net.sf.jasperreports.engine.fill.JRFillBand.evaluate(JRFillBand.java:456) ~[jasperreports-5.5.0.jar:5.5.0]
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillSummaryNoLastFooterSamePage(JRVerticalFiller.java:1090) ~[jasperreports-5.5.0.jar:5.5.0]
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillSummary(JRVerticalFiller.java:1055) ~[jasperreports-5.5.0.jar:5.5.0]
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReportEnd(JRVerticalFiller.java:319) ~[jasperreports-5.5.0.jar:5.5.0]
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReport(JRVerticalFiller.java:158) ~[jasperreports-5.5.0.jar:5.5.0]
        at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:932) ~[jasperreports-5.5.0.jar:5.5.0]
        at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:864) ~[jasperreports-5.5.0.jar:5.5.0]
        at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:114) ~[jasperreports-5.5.0.jar:5.5.0]
        at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:653) ~[jasperreports-5.5.0.jar:5.5.0]
        at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:569) ~[jasperreports-5.5.0.jar:5.5.0]
        at org.mapfish.print.output.AbstractJasperReportOutputFormat.getJasperPrint(AbstractJasperReportOutputFormat.java:209) ~[AbstractJasperReportOutputFormat.class:na]
        at org.mapfish.print.output.AbstractJasperReportOutputFormat.print(AbstractJasperReportOutputFormat.java:109) ~[AbstractJasperReportOutputFormat.class:na]
        at org.mapfish.print.MapPrinter.print(MapPrinter.java:138) ~[MapPrinter.class:na]
        at org.mapfish.print.servlet.job.PrintJob$1.run(PrintJob.java:116) ~[PrintJob$1.class:na]
        at org.mapfish.print.servlet.job.FilePrintJob.withOpenOutputStream(FilePrintJob.java:50) ~[FilePrintJob.class:na]
        at org.mapfish.print.servlet.job.PrintJob.call(PrintJob.java:113) [PrintJob.class:na]
        at org.mapfish.print.servlet.job.PrintJob.call(PrintJob.java:54) [PrintJob.class:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_65]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_65]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_65]
17:14:32.202 [http-8080-1] ERROR o.m.print.servlet.BaseMapServlet - Error while processing request: java.lang.IllegalStateException: Target host is null
```

**Comment by zhujianguang** [comment]
请问这个问题是如何解决的？
