### ISSUE TITLE
Get 403 forbidden on base layer OSM 

### ISSUE THREAD

**Issue by garciasa** [mapfish/mapfish-print#1677]
- MapFish print version: 3.24
- Java version: 1.8.0_102
- OS: Windows Server 2012

Hello everyone,
We have using the OSM tile server for the last while. We use it to background maps in some user pdf reports generated by mapfish. 10 days ago, mapfish has been started to not show the OSM base layer, the rest of the pdf is correct.

We're receiving 403 forbidden errors even when we try to generate examples reports from the test print page (which they were working before).

```
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Error making tile request: http://tile.openstreetmap.org/8/119/84.png
	Status: 403 FORBIDDEN
	outMessage: Forbidden
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at org.mapfish.print.output.AbstractJasperReportOutputFormat.getJasperPrint(AbstractJasperReportOutputFormat.java:147)
	at org.mapfish.print.output.AbstractJasperReportOutputFormat.print(AbstractJasperReportOutputFormat.java:94)
	at org.mapfish.print.MapPrinter.print(MapPrinter.java:133)
	at org.mapfish.print.servlet.job.PrintJob.lambda$call$0(PrintJob.java:148)
	at org.mapfish.print.servlet.job.PrintJob.withOpenOutputStream(PrintJob.java:118)
	at org.mapfish.print.servlet.job.PrintJob.call(PrintJob.java:147)
	at org.mapfish.print.servlet.job.PrintJob.call(PrintJob.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Error making tile request: http://tile.openstreetmap.org/8/119/84.png
	Status: 403 FORBIDDEN
	outMessage: Forbidden
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	... 11 common frames omitted
```

After digging a little bit more we have seen this tweet from OSM_Tech https://twitter.com/OSM_Tech/status/1343976097067782145
but our print service is not using proxy (just a firewall) and there is not log blocking anything.

As far as I know mapfish itself is acting as proxy but we have added this to the config file to make sure referer and user-agent is  same as the client. If mapfish is acting as proxy for those request, that change they OSM team suggests is not affecting us?

```
 - !configureHttpRequests
        httpProcessors:
          - !forwardHeaders
            headers:
              - Referer
              - User-Agent
              - Host    
```
            
we have also added Host in the forwardedHeaders  to try making some request setting host header manually from the client to tile.openstreetmap.org as they suggested in that tweet, but same result.

Any feedback is welcome.

Thank you in advance.

**Comment by garciasa** [comment]
Hi this is a confirmation from OSM that something has changed around Christmas time, and for some reason mapfish is not getting OSM base layers related to Host header...

`Around Christmas we switched CDNs in Europe, so broken proxies that were sending the wrong Host header would have stopped working about then.`

If I'm right, with !forwardHeaders (Referer, User-Agent, Host) Mapfish should be able to inject the incoming headers from the client into the request is going to do to the external layers, isn't it?

Thanks in advance.

**Comment by sbrunner** [comment]
Yes :-)

**Comment by garciasa** [comment]
Problem solved! my bad, the order of preprocessors matters :).
Now it's working...
