### ISSUE TITLE
Caused by: java.awt.image.RasterFormatException: negative or zero width

### ISSUE THREAD

**Issue by bhoefling-c2c** [mapfish/mapfish-print#1879]
```
00:08:44.033 [ForkJoinPool-1-worker-229] INFO  o.m.p.processor.ProcessorGraphNode - Time taken to run processor: 'class org.mapfish.print.processor.map.CreateMapProcessor' was 1522 ms
Exception in thread "main" java.util.concurrent.ExecutionException: java.awt.image.RasterFormatException: negative or zero width
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at org.mapfish.print.output.AbstractJasperReportOutputFormat.getJasperPrint(AbstractJasperReportOutputFormat.java:147)
	at org.mapfish.print.output.AbstractJasperReportOutputFormat.print(AbstractJasperReportOutputFormat.java:94)
	at org.mapfish.print.MapPrinter.print(MapPrinter.java:133)
	at org.mapfish.print.cli.Main.run(Main.java:201)
	at org.mapfish.print.cli.Main.runMain(Main.java:111)
	at org.mapfish.print.cli.Main.main(Main.java:65)
Caused by: java.awt.image.RasterFormatException: negative or zero width
	at java.desktop/java.awt.image.Raster.<init>(Raster.java:1192)
	at java.desktop/java.awt.image.WritableRaster.<init>(WritableRaster.java:129)
	at java.desktop/sun.awt.image.SunWritableRaster.<init>(SunWritableRaster.java:129)
	at java.desktop/sun.awt.image.ByteComponentRaster.<init>(ByteComponentRaster.java:155)
	at java.desktop/sun.awt.image.ByteInterleavedRaster.<init>(ByteInterleavedRaster.java:192)
	at java.desktop/sun.awt.image.ByteInterleavedRaster.createWritableChild(ByteInterleavedRaster.java:1256)
	at java.desktop/java.awt.image.BufferedImage.getSubimage(BufferedImage.java:1202)
	at org.mapfish.print.map.tiled.CoverageTask.call(CoverageTask.java:113)
	at org.mapfish.print.map.tiled.AbstractTiledLayer.getLayers(AbstractTiledLayer.java:96)
	at org.mapfish.print.map.geotools.AbstractGeotoolsLayer.render(AbstractGeotoolsLayer.java:88)
	at org.mapfish.print.processor.map.CreateMapProcessor.createLayerGraphics(CreateMapProcessor.java:448)
	at org.mapfish.print.processor.map.CreateMapProcessor.execute(CreateMapProcessor.java:239)
	at org.mapfish.print.processor.map.CreateMapProcessor.execute(CreateMapProcessor.java:100)
	at org.mapfish.print.processor.ProcessorGraphNode$ProcessorNodeForkJoinTask.lambda$compute$0(ProcessorGraphNode.java:203)
	at org.mapfish.print.processor.AbstractProcessor$Context.mdcContext(AbstractProcessor.java:240)
	at org.mapfish.print.processor.ProcessorGraphNode$ProcessorNodeForkJoinTask.compute(ProcessorGraphNode.java:188)
	at org.mapfish.print.processor.ProcessorDependencyGraph.tryExecuteNodes(ProcessorDependencyGraph.java:58)
	at org.mapfish.print.processor.ProcessorGraphNode$ProcessorNodeForkJoinTask.lambda$compute$0(ProcessorGraphNode.java:225)
	at org.mapfish.print.processor.AbstractProcessor$Context.mdcContext(AbstractProcessor.java:240)
	at org.mapfish.print.processor.ProcessorGraphNode$ProcessorNodeForkJoinTask.compute(ProcessorGraphNode.java:188)
	at org.mapfish.print.processor.ProcessorGraphNode$ProcessorNodeForkJoinTask.compute(ProcessorGraphNode.java:176)
	at java.base/java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
00:08:44.150 [ForkJoinPool-2-worker-31] INFO  o.a.http.impl.execchain.RetryExec - I/O exception (java.net.SocketException) caught when processing request to {}->http://localhost:8088: Socket closed
00:08:44.151 [ForkJoinPool-2-worker-31] INFO  o.a.http.impl.execchain.RetryExec - Retrying request to {}->http://localhost:8088

```

json:

```
{
  "layout": "Auto meta tiling",
  "outputFormat": "png",
  "attributes": {
    "map": {
      "dpi": 72,
      "rotation": 0,
      "center": [
        696806,
        5329497
      ],
      "scale": 40000,
      "projection": "EPSG:25832",
      "longitudeFirst": true,
      "layers": [
        {
          "type": "WMS",
          "baseURL": "http://localhost:8088/geoserver/by/wms",
          "opacity": 1,
          "serverType": "geoserver",
          "layers": [
            "by:gemeinden"
          ],
          "imageFormat": "image/png",
          "customParams": {
            "TRANSPARENT": "true"
          }
        }
      ]
    }
  }
}

```

config.yaml:
```
templates:
  Auto meta tiling: !template
    #===========================================================================
    reportTemplate: report.jrxml
    attributes:
      title: !string
        default: ''
      map: !map
        maxDpi: 400
        width: 1000
        height: 1000
      northArrow: !northArrow
        size: 200
        default:
          graphic: 'north.svg'
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !setTiledWms
      maxWidth: 256
      maxHeight: 256
      tileBufferWidth: 61
      tileBufferHeight: 62
    - !createMap {}
    - !createNorthArrow {}

```

**Comment by bhoefling-c2c** [comment]
Debugging:

```
    public BufferedImage getSubimage (int x, int y, int w, int h) {
        return new BufferedImage (colorModel,
                                  raster.createWritableChild(x, y, w, h,
                                                             0, 0, null),
                                  colorModel.isAlphaPremultiplied(),
                                  properties);
    }
```

Either w 0r h was zero. Crash!
