### ISSUE TITLE
Legend don't works with stange message

### ISSUE THREAD

**Issue by sbrunner** [mapfish/mapfish-print#195]
Project datas: 
https://github.com/camptocamp/demo_geomapfish/tree/printV3/print/print-apps/demo

Result:
```

12:52:21.747 [http-8080-1] INFO  p.mapfish.print.servlet.spec - spec:
        {"outputFormat":"pdf","layout":"A4 portrait old api","attributes":{"title":"","legend":[{"classes":[{"name":"hospitals","icons":["http://geomapfish.demo-camptocamp.com/sbrunner/wsgi/mapserv_proxy?TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetLegendGraphic&EXCEPTIONS=application%2Fvnd.ogc.se_xml&LAYER=hospitals&FORMAT=image%2Fpng&SCALE=100000"]}],"name":""}],"gridList":[],"map":{"center":[542000,154000],"scale":100000,"rotation":0,"layers":[],"projection":"EPSG:21781","dpi":254,"longitudeFirst":true},"comments":""}}
12:52:21.758 [ForkJoinPool-1-worker-2] INFO  o.m.p.processor.ProcessorGraphNode - Executing process: JasperReportBuilder(/srv/tomcat/tomcat1/webapps/print-demo-sbrunner/print-apps/demo/.)
12:52:21.758 [ForkJoinPool-1-worker-3] INFO  o.m.p.processor.ProcessorGraphNode - Executing process: LegendProcessor
12:52:21.758 [ForkJoinPool-1-worker-3] INFO  o.m.p.processor.ProcessorGraphNode - Succeeded in executing process: LegendProcessor
12:52:21.758 [ForkJoinPool-1-worker-2] INFO  o.m.p.processor.ProcessorGraphNode - Succeeded in executing process: JasperReportBuilder(/srv/tomcat/tomcat1/webapps/print-demo-sbrunner/print-apps/demo/.)
12:52:21.759 [ForkJoinPool-1-worker-4] INFO  o.m.p.processor.ProcessorGraphNode - Executing process: CreateMapProcessor
12:52:21.815 [ForkJoinPool-1-worker-4] INFO  o.m.p.processor.ProcessorGraphNode - Succeeded in executing process: CreateMapProcessor
12:52:21.831 [PrintJobManager-2] INFO  o.mapfish.print.servlet.job.PrintJob - Error executing print job f8a0f43a-07d7-47d4-9d4a-5e55258ff22b@3c94c543-d2a7-4d5d-be7b-66dcc4d39f7b
spec:
        {"app":"demo","outputFormat":"pdf","layout":"A4 portrait old api","attributes":{"title":"","requestHeaders":{"requestHeaders":{"content-type":["application/json; charset=UTF-8"],"connection":["close"],"accept-language":["fr,fr-fr;q=0.8,en-us;q=0.5,en;q=0.3"],"host":["geomapfish.demo-camptocamp.com"],"accept":["text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"],"user-agent":["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0"],"dnt":["1"],"pragma":["no-cache"],"cookie":["auth_tkt_sbrunner=\"618f9243f4a5f9ae016047b265ecc8df0e45c7465ee0fd157ca235f6d89f5916517e5f0a2e1db012d6939680ea23f8adf48e16471761e1f6ba3ab026b033812454e44caeYWRtaW4%3D!userid_type:b64unicode\"; auth_tkt_sbrunner=\"618f9243f4a5f9ae016047b265ecc8df0e45c7465ee0fd157ca235f6d89f5916517e5f0a2e1db012d6939680ea23f8adf48e16471761e1f6ba3ab026b033812454e44caeYWRtaW4%3D!userid_type:b64unicode\""],"cache-control":["no-cache"],"content-length":["528"],"accept-encoding":["gzip, deflate"],"referer":["http://geomapfish.demo-camptocamp.com/sbrunner/theme/Administration?map_x=542000&map_y=154000&map_zoom=0&debug"],"x-requested-with":["XMLHttpRequest"]}},"legend":[{"classes":[{"name":"hospitals","icons":["http://geomapfish.demo-camptocamp.com/sbrunner/wsgi/mapserv_proxy?TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetLegendGraphic&EXCEPTIONS=application%2Fvnd.ogc.se_xml&LAYER=hospitals&FORMAT=image%2Fpng&SCALE=100000"]}],"name":""}],"gridList":[],"map":{"center":[542000,154000],"scale":100000,"rotation":0,"layers":[],"projection":"EPSG:21781","dpi":254,"longitudeFirst":true},"comments":""}}
com.vividsolutions.jts.util.AssertionFailedException: The following parameters are declared in A4_Portrait.jrxml but are not output values of processors or attributes.
Either remove the references or update the configuration so that all the parameters are available for the report.

        * legendSubReport

        at org.mapfish.print.output.AbstractJasperReportOutputFormat.checkRequiredValues(AbstractJasperReportOutputFormat.java:318) ~[AbstractJasperReportOutputFormat.class:na]
        at org.mapfish.print.output.AbstractJasperReportOutputFormat.getJasperPrint(AbstractJasperReportOutputFormat.java:170) ~[AbstractJasperReportOutputFormat.class:na]
        at org.mapfish.print.output.AbstractJasperReportOutputFormat.print(AbstractJasperReportOutputFormat.java:109) ~[AbstractJasperReportOutputFormat.class:na]
        at org.mapfish.print.MapPrinter.print(MapPrinter.java:138) ~[MapPrinter.class:na]
        at org.mapfish.print.servlet.job.PrintJob$1.run(PrintJob.java:116) ~[PrintJob$1.class:na]
        at org.mapfish.print.servlet.job.FilePrintJob.withOpenOutputStream(FilePrintJob.java:50) ~[FilePrintJob.class:na]
        at org.mapfish.print.servlet.job.PrintJob.call(PrintJob.java:113) [PrintJob.class:na]
        at org.mapfish.print.servlet.job.PrintJob.call(PrintJob.java:54) [PrintJob.class:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_75]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
```

**Comment by jesseeichar** [comment]
Did you get this before or after you commented out the <parameter name="legendSubReport" class="java.lang.String"/--> line?

because this means that the jrxml has a parameter legendSubReport which is not a value in the Values object.

Although given that there is an output of !prepareLegend, it is a bit surprising that it is not in values.

**Comment by sbrunner** [comment]
Effectively it's before I commented the line :-), I commented the line to go ahead.

**Comment by jesseeichar** [comment]
Can I close this issue since it seems the error was the jrxml file and not mfp?

**Comment by sbrunner** [comment]
... what the solution ?

**Comment by jesseeichar** [comment]
Legend has an output which is the legendSubReport but it is null unless the legend's template configuration parameter is declared.  Thus (naturally) the legend did not exist.

**Comment by jesseeichar** [comment]
I have added logging so that you can see exactly what values are in the Values object before the template is rendered.
