### ISSUE TITLE
print-apps does not refer to a file on the current system with Tomcat .war

### ISSUE THREAD

**Issue by RussellGrew** [mapfish/mapfish-print#2279]
**Context**

- MapFish print version: 3.28, 3.28.2
- Java version: OpenJDK 11
- Tomcat 8.5 64 bit
- OS: Windows Server 2016

**Describe the bug**

When copying the .war file into Tomcat it doesn't start.

**How to reproduce**

Copy .war file into Tomcat web apps.

**Actual results**

See error from Tomcat 8 stdout

```
gradle: 10:03:36.375 [localhost-startStop-3] ERROR o.s.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mapPrinterFactory' defined in ServletContext resource [/WEB-INF/mapfish-print-printer-factory.xml]: Error setting property values; nested exception is org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'appsRootDirectory' threw exception; nested exception is java.lang.IllegalArgumentException: servlet:///print-apps does not refer to a file on the current system.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1736)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1444)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4701)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5167)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1841)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.springframework.beans.PropertyBatchUpdateException: Failed properties: Property 'appsRootDirectory' threw exception; nested exception is java.lang.IllegalArgumentException: servlet:///print-apps does not refer to a file on the current system.
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:122)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:77)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1732)
	... 26 common frames omitted

```

Many thanks for any assistance.

Looking at https://github.com/mapfish/mapfish-print/blob/befa4bbf53e646d457fa85b127cf598baa5fc8d2/core/src/main/resources/mapfish-spring.properties I can experiment with setting environment variables if this is helpful.

**Comment by sbrunner** [comment]
Can't you set the `printapps.location` in your project?

**Comment by Revo86** [comment]
I'm having the exact same issue. All I did was copying the war file and booting up tomcat9.

**Comment by sbrunner** [comment]
For me, the @Revo86 Looks to be the good solution ;-) , closing

**Comment by RussellGrew** [comment]
Many thanks @Revo86 

Apologies for letting this slip.

For anyone else who may be reading this, the print-apps folder you need to create looks like

`...\Apache Software Foundation\Tomcat 8.5\webapps\print-servlet-3.29.2\print-apps`

And then the test print page is at 

`http://localhost:8080/print-servlet-3.29.2/`

Where I suppose the version number will depend on circumstances.
