### ISSUE TITLE
Incompatibility issue between related file to config and `useHttpForHttps`

### ISSUE THREAD

**Issue by sbrunner** [mapfish/mapfish-print#228]
Config:
```
        attributes:
            northArrow: !northArrow
                size: 40
                default:
                    graphic: "north.svg"
            ...
        processors:
        ...
        - !configureHttpRequests
            httpProcessors:
            - !mapUri
                mapping:
                    ([htps]+)://geomapfish.demo-camptocamp.com/(.*): "$1://127.0.0.1/$2"
            - !useHttpForHttps
                hosts:
                - geomapfish.demo-camptocamp.com
                portMapping:
                    443: 80
            - !forwardHeaders
                headers:
                - Cookie
                - Host
                - Referrer
        ...
        - !createNorthArrow {}
        ...
```
Logs:
```
...
Caused by: java.lang.NullPointerException: null
        at org.mapfish.print.processor.http.UseHttpForHttpsProcessor$1.createRequest(UseHttpForHttpsProcessor.java:87) ~[UseHttpForHttpsProcessor$1.class:na]
        at org.mapfish.print.http.AbstractMfClientHttpRequestFactoryWrapper.createRequest(AbstractMfClientHttpRequestFactoryWrapper.java:57) ~[AbstractMfClientHttpRequestFactoryWrapper.class:na]
        at org.mapfish.print.processor.http.MapUriProcessor$1.createRequest(MapUriProcessor.java:87) ~[MapUriProcessor$1.class:na]
        at org.mapfish.print.http.AbstractMfClientHttpRequestFactoryWrapper.createRequest(AbstractMfClientHttpRequestFactoryWrapper.java:57) ~[AbstractMfClientHttpRequestFactoryWrapper.class:na]
        at org.mapfish.print.processor.map.NorthArrowGraphic.loadGraphic(NorthArrowGraphic.java:124) ~[NorthArrowGraphic.class:na]
        at org.mapfish.print.processor.map.NorthArrowGraphic.create(NorthArrowGraphic.java:95) ~[NorthArrowGraphic.class:na]
        at org.mapfish.print.processor.map.CreateNorthArrowProcessor.execute(CreateNorthArrowProcessor.java:95) ~[CreateNorthArrowProcessor.class:na]
        at org.mapfish.print.processor.map.CreateNorthArrowProcessor.execute(CreateNorthArrowProcessor.java:68) ~[CreateNorthArrowProcessor.class:na]
        at org.mapfish.print.processor.ProcessorGraphNode$ProcessorNodeForkJoinTask.compute(ProcessorGraphNode.java:210) ~[ProcessorGraphNode$ProcessorNodeForkJoinTask.class:na]
        ... 7 common frames omitted
```

**Comment by tsauerwein** [comment]
It's probably not related to your problem, but you are missing a "t" in `([htps])://${host}/(.*)`.

**Comment by sbrunner** [comment]
no because it's a regex ..., but `${host}` should be a host name, I just replace it by `my_host`

**Comment by jesseeichar** [comment]
Shouldn't the regex be:  ([htps]+)://${host}/(.*)

**Comment by sbrunner** [comment]
Effectively @jesseeichar , but now I have two issue:
the first is nearly the same:
```
11:52:03.592 [ForkJoinPool-1-worker-14] INFO  o.m.p.processor.ProcessorGraphNode - Executing process: CreateNorthArrowProcessor
11:52:03.594 [ForkJoinPool-1-worker-14] ERROR o.m.p.processor.ProcessorGraphNode - Error while executing process: CreateNorthArrowProcessor
java.lang.NullPointerException: null
        at org.mapfish.print.processor.http.UseHttpForHttpsProcessor$1.createRequest(UseHttpForHttpsProcessor.java:87) ~[UseHttpForHttpsProcessor$1.class:na]
        at org.mapfish.print.http.AbstractMfClientHttpRequestFactoryWrapper.createRequest(AbstractMfClientHttpRequestFactoryWrapper.java:57) ~[AbstractMfClientHttpRequestFactoryWrapper.class:na]
        at org.mapfish.print.processor.http.MapUriProcessor$1.createRequest(MapUriProcessor.java:87) ~[MapUriProcessor$1.class:na]
        at org.mapfish.print.http.AbstractMfClientHttpRequestFactoryWrapper.createRequest(AbstractMfClientHttpRequestFactoryWrapper.java:57) ~[AbstractMfClientHttpRequestFactoryWrapper.class:na]
        at org.mapfish.print.processor.map.NorthArrowGraphic.loadGraphic(NorthArrowGraphic.java:124) ~[NorthArrowGraphic.class:na]
        at org.mapfish.print.processor.map.NorthArrowGraphic.create(NorthArrowGraphic.java:95) ~[NorthArrowGraphic.class:na]
        at org.mapfish.print.processor.map.CreateNorthArrowProcessor.execute(CreateNorthArrowProcessor.java:95) ~[CreateNorthArrowProcessor.class:na]
        at org.mapfish.print.processor.map.CreateNorthArrowProcessor.execute(CreateNorthArrowProcessor.java:68) ~[CreateNorthArrowProcessor.class:na]
        at org.mapfish.print.processor.ProcessorGraphNode$ProcessorNodeForkJoinTask.compute(ProcessorGraphNode.java:210) [ProcessorGraphNode$ProcessorNodeForkJoinTask.class:na]
        at org.mapfish.print.processor.ProcessorGraphNode$ProcessorNodeForkJoinTask.compute(ProcessorGraphNode.java:187) [ProcessorGraphNode$ProcessorNodeForkJoinTask.class:na]
        at jsr166y.RecursiveTask.exec(RecursiveTask.java:64) [jsr166y-1.7.0.jar:1.7.0]
        at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:305) [jsr166y-1.7.0.jar:1.7.0]
        at jsr166y.ForkJoinWorkerThread.execTask(ForkJoinWorkerThread.java:575) [jsr166y-1.7.0.jar:1.7.0]
        at jsr166y.ForkJoinPool.scan(ForkJoinPool.java:733) [jsr166y-1.7.0.jar:1.7.0]
        at jsr166y.ForkJoinPool.work(ForkJoinPool.java:617) [jsr166y-1.7.0.jar:1.7.0]
        at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:369) [jsr166y-1.7.0.jar:1.7.0]
```

And the second looks like that the host is replaced (`mapUri`), but the `Host` header isn't forwarded (`forwardHeaders`), the url is in main apache access log but not in the vhost acces log ... :
```
Caused by: com.vividsolutions.jts.util.AssertionFailedException: Expected 200 but encountered 404: Http status code for http://geomapfish.demo-camptocamp.com/sbrunner/wsgi/mapserv_proxy?TRANSPARENT=true&BBOX=532240.4166666666%2C141673.75%2C551819.5833333333%2C165486.25&VERSION=1.1.1&FORMAT=image%2Fpng&SERVICE=WMS&HEIGHT=2381&REQUEST=GetMap&LAYERS=fuel&STYLES=&SRS=EPSG%3A21781&WIDTH=1957 was not OK.  It was: 404.  The response message was: 'Not Found'
        at com.vividsolutions.jts.util.Assert.equals(Assert.java:100) ~[jts-1.13.jar:na]
        at org.mapfish.print.map.image.wms.WmsLayer.loadImage(WmsLayer.java:85) ~[WmsLayer.class:na]
        at org.mapfish.print.map.image.AbstractSingleImageLayer.getLayers(AbstractSingleImageLayer.java:72) ~[AbstractSingleImageLayer.class:na]
        at org.mapfish.print.map.geotools.AbstractGeotoolsLayer.render(AbstractGeotoolsLayer.java:97) ~[AbstractGeotoolsLayer.class:na]
        at org.mapfish.print.processor.map.CreateMapProcessor.createLayerGraphics(CreateMapProcessor.java:224) ~[CreateMapProcessor.class:na]
        at org.mapfish.print.processor.map.CreateMapProcessor.execute(CreateMapProcessor.java:157) ~[CreateMapProcessor.class:na]
        at org.mapfish.print.processor.map.CreateMapProcessor.execute(CreateMapProcessor.java:100) ~[CreateMapProcessor.class:na]
        at org.mapfish.print.processor.ProcessorGraphNode$ProcessorNodeForkJoinTask.compute(ProcessorGraphNode.java:210) ~[ProcessorGraphNode$ProcessorNodeForkJoinTask.class:na]
        at org.mapfish.print.processor.ProcessorGraphNode$ProcessorNodeForkJoinTask.executeDependencyProcessors(ProcessorGraphNode.java:259) ~[ProcessorGraphNode$ProcessorNodeForkJoinTask.class:na]
        at org.mapfish.print.processor.ProcessorGraphNode$ProcessorNodeForkJoinTask.compute(ProcessorGraphNode.java:235) ~[ProcessorGraphNode$ProcessorNodeForkJoinTask.class:na]
        at org.mapfish.print.processor.ProcessorGraphNode$ProcessorNodeForkJoinTask.compute(ProcessorGraphNode.java:187) ~[ProcessorGraphNode$ProcessorNodeForkJoinTask.class:na]
        at jsr166y.RecursiveTask.exec(RecursiveTask.java:64) ~[jsr166y-1.7.0.jar:1.7.0]
        at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:305) ~[jsr166y-1.7.0.jar:1.7.0]
        at jsr166y.ForkJoinWorkerThread.execTask(ForkJoinWorkerThread.java:575) ~[jsr166y-1.7.0.jar:1.7.0]
        at jsr166y.ForkJoinPool.scan(ForkJoinPool.java:733) ~[jsr166y-1.7.0.jar:1.7.0]
        ... 2 common frames omitted
```

**Comment by jesseeichar** [comment]
I am having a problem reproducing this issue in tests.  Could you provide an example json request that triggers this issue?

**Comment by jesseeichar** [comment]
The problem seems to be related to the north arrow graphic parameter.  Do you know what it is?  Again json post request will help

**Comment by sbrunner** [comment]
I didn't sent anything in the json post about the noth arrow in the json post (everything is in the attribute default), than do you want a full json post ?

**Comment by jesseeichar** [comment]
Please give me the full json and maybe link me to the config.yaml that is used.

**Comment by sbrunner** [comment]
Config:
```
throwErrorOnExtraParameters: true

templates:
    A4 portrait: !template
        reportTemplate: A4_Portrait.jrxml
        attributes:
            title: !string
                default: ""
            comments: !string
                default: ""
            debug: !integer
                default: 0
            legend: !legend {}
            northArrow: !northArrow
                size: 40
                default:
                    graphic: "north.svg"
            scalebar: !scalebar
                width: 150
                height: 20
                default:
                     fontSize: 8
            map: !map
                maxDpi: 254
                dpiSuggestions: [254]
                zoomLevels: !zoomLevels
                    scales: [100, 250, 500, 2500, 5000, 10000, 25000, 50000, 100000, 500000]
                width: 555
                height: 675
            datasource: !datasource
                attributes:
                    title: !string {}
                    table: !table {}

        processors:
        - !reportBuilder # compile all reports in current directory
            directory: '.'
        - !configureHttpRequests
            httpProcessors:
            - !mapUri
                mapping:
                    ([htps])://geomapfish.demo-camptocamp.com/(.*): "$1://127.0.0.1/$2"
            - !useHttpForHttps
                hosts:
                - geomapfish.demo-camptocamp.com
                portMapping:
                    443: 80
            - !forwardHeaders
                headers:
                - Cookie
                - Host
                - Referrer
        - !prepareLegend
            template: legend.jrxml
        - !createNorthArrow {}
        - !createScalebar {}
        - !createMap {}
        - !createDataSource
            processors:
            - !prepareTable
                dynamic: true
                columns:
                    icon: !urlImage
                        urlExtractor: (.*)
                        urlGroup: 1
```
Spec:
```
{"layout":"A4 portrait","outputFormat":"pdf","attributes":{"title":"","comments":"","debug":"0","datasource":[],"map":{"projection":"EPSG:21781","dpi":254,"rotation":0,"center":[542000,154000],"scale":100000,"longitudeFirst":true,"layers":[{"baseURL":"http://geomapfish.demo-camptocamp.com/1.6/wsgi/mapserv_proxy","opacity":1,"type":"wms","layers":["fuel"],"imageFormat":"image/png","styles":[""],"customParams":{"TRANSPARENT":true}},{"baseURL":"http://ows.asitvd.ch/wmts/1.0.0/asitvd.fond_couleur/default/{DIM1}/{ELEVATION}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}.png","opacity":1,"type":"wmts","layer":"asitvd.fond_couleur","version":"1.0.0","requestEncoding":"REST","style":"default","dimensions":["DIM1","ELEVATION"],"dimensionParams":{"DIM1":"default","ELEVATION":"0"},"matrixSet":"21781","imageFormat":"image/png","matrices":[{"identifier":0,"matrixSize":[1,1],"scaleDenominator":14285714.285714287,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":1,"matrixSize":[1,1],"scaleDenominator":13392857.142857142,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":2,"matrixSize":[1,1],"scaleDenominator":12500000,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":3,"matrixSize":[1,1],"scaleDenominator":11607142.857142856,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":4,"matrixSize":[1,1],"scaleDenominator":10714285.714285713,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":5,"matrixSize":[1,1],"scaleDenominator":9821428.571428573,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":6,"matrixSize":[1,1],"scaleDenominator":8928571.428571427,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":7,"matrixSize":[1,1],"scaleDenominator":8035714.285714286,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":8,"matrixSize":[1,1],"scaleDenominator":7142857.142857144,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":9,"matrixSize":[2,1],"scaleDenominator":6250000,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":10,"matrixSize":[2,1],"scaleDenominator":5357142.857142856,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":11,"matrixSize":[2,1],"scaleDenominator":4464285.714285714,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":12,"matrixSize":[2,2],"scaleDenominator":3571428.571428572,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":13,"matrixSize":[3,2],"scaleDenominator":2678571.428571428,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":14,"matrixSize":[3,2],"scaleDenominator":2321428.571428572,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":15,"matrixSize":[4,3],"scaleDenominator":1785714.285714286,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":16,"matrixSize":[8,5],"scaleDenominator":892857.142857143,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":17,"matrixSize":[19,13],"scaleDenominator":357142.85714285716,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":18,"matrixSize":[38,25],"scaleDenominator":178571.42857142858,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":19,"matrixSize":[94,63],"scaleDenominator":71428.57142857143,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":20,"matrixSize":[188,125],"scaleDenominator":35714.28571428572,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":21,"matrixSize":[375,250],"scaleDenominator":17857.14285714286,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":22,"matrixSize":[750,500],"scaleDenominator":8928.57142857143,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":23,"matrixSize":[938,625],"scaleDenominator":7142.857142857143,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":24,"matrixSize":[1250,834],"scaleDenominator":5357.142857142858,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":25,"matrixSize":[1875,1250],"scaleDenominator":3571.4285714285716,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":26,"matrixSize":[3750,2500],"scaleDenominator":1785.7142857142858,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":27,"matrixSize":[7500,5000],"scaleDenominator":892.8571428571429,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":28,"matrixSize":[18750,12500],"scaleDenominator":357.14285714285717,"tileSize":[256,256],"topLeftCorner":[420000,350000]},{"identifier":29,"matrixSize":[37500,25000],"scaleDenominator":178.57142857142858,"tileSize":[256,256],"topLeftCorner":[420000,350000]}]}]},"legend":{"classes":[{"name":"","classes":[{"name":"fuel","icons":["http://geomapfish.demo-camptocamp.com/1.6/wsgi/mapserv_proxy?TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetLegendGraphic&EXCEPTIONS=application%2Fvnd.ogc.se_xml&LAYER=fuel&FORMAT=image%2Fpng&SCALE=100000"]}]}]}}}
```

**Comment by jesseeichar** [comment]
a quick fix would be to change:

            northArrow: !northArrow
                size: 40
                default:
                    graphic: "north.svg"

to

            northArrow: !northArrow
                size: 40
                default:
                    graphic: "file://north.svg"

**Comment by jesseeichar** [comment]
but the current configuration should work.  I will update my test to test the case where the north arrow graphic does not have file://

**Comment by sbrunner** [comment]
Looks good, thanks ;-)

**Comment by sbrunner** [comment]
I steal have the issue but the workaround works ...
