### ISSUE TITLE
The print server takes 150% of CPU in backaground ...

### ISSUE THREAD

**Issue by sbrunner** [mapfish/mapfish-print#299]

**Comment by sbrunner** [comment]
logs:
```
14:56:41,429 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
14:56:41,429 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
14:56:41,430 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/srv/tomcat/tomcat1/webapps/print-nyon_airport_demo/WEB-INF/classes/logback.xml]
14:56:41,501 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
14:56:41,505 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
14:56:41,519 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [standardOut]
14:56:41,602 |-WARN in ch.qos.logback.core.ConsoleAppender[standardOut] - This appender no longer admits a layout as a sub-component, set an encoder instead.
14:56:41,602 |-WARN in ch.qos.logback.core.ConsoleAppender[standardOut] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
14:56:41,602 |-WARN in ch.qos.logback.core.ConsoleAppender[standardOut] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
14:56:41,602 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
14:56:41,606 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [File]
14:56:41,630 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
14:56:41,633 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern build/logs/logFile.%d{yyyy-MM-dd}.log for the active file
14:56:41,639 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern 'build/logs/logFile.%d{yyyy-MM-dd}.log'.
14:56:41,639 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
14:56:41,639 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Wed Aug 19 14:56:41 CEST 2015
14:56:41,642 |-WARN in ch.qos.logback.core.rolling.RollingFileAppender[File] - This appender no longer admits a layout as a sub-component, set an encoder instead.
14:56:41,642 |-WARN in ch.qos.logback.core.rolling.RollingFileAppender[File] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
14:56:41,642 |-WARN in ch.qos.logback.core.rolling.RollingFileAppender[File] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
14:56:41,645 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[File] - Active log file name: build/logs/logFile.log
14:56:41,645 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[File] - File property is set to [build/logs/logFile.log]
14:56:41,647 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[File] - Failed to create parent directories for [/srv/tomcat/tomcat1/build/logs/logFile.log]
14:56:41,647 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[File] - openFile(build/logs/logFile.log,true) call failed. java.io.FileNotFoundException: build/logs/logFile.log (No such file or directory)
        at java.io.FileNotFoundException: build/logs/logFile.log (No such file or directory)
        at      at java.io.FileOutputStream.open(Native Method)
        at      at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at      at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:28)
        at      at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:149)
        at      at ch.qos.logback.core.FileAppender.start(FileAppender.java:108)
        at      at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:86)
        at      at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:96)
        at      at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
        at      at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
        at      at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
        at      at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
        at      at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
        at      at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
        at      at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
        at      at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
        at      at org.slf4j.LoggerFactory.bind(LoggerFactory.java:129)
        at      at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:108)
        at      at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:302)
        at      at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:276)
        at      at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:288)
        at      at org.mapfish.print.config.WorkingDirectories.<clinit>(WorkingDirectories.java:38)
        at      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at      at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at      at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148)
        at      at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
        at      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1030)
        at      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:983)
        at      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:487)
        at      at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
        at      at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:296)
        at      at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
        at      at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:293)
        at      at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at      at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:628)
        at      at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
        at      at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
        at      at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
        at      at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
        at      at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
        at      at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4797)
        at      at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5221)
        at      at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at      at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
        at      at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
        at      at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
        at      at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:919)
        at      at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1703)
        at      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at      at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at      at java.lang.Thread.run(Thread.java:745)
14:56:41,649 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.mapfish] to DEBUG
14:56:41,649 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework] to OFF
14:56:41,649 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.mapfish.print.servlet.BaseMapServlet.spec] to OFF
14:56:41,649 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.codahale.metrics] to INFO
14:56:41,649 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.codahale.metrics.JmxReporter] to INFO
14:56:41,649 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to ALL
14:56:41,649 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [standardOut] to Logger[ROOT]
14:56:41,650 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [File] to Logger[ROOT]
14:56:41,650 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
14:56:41,652 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@55aa6ddc - Registering current configuration as safe fallback point
```
