### ISSUE TITLE
The print takes about 10 minutes to start...

### ISSUE THREAD

**Issue by sbrunner** [mapfish/mapfish-print#312]
Tested on geomapfish demo server with 3 instances.

**Comment by elemoine** [comment]
What do you mean by "start"? I guess this would deserve a bit more explanations.

**Comment by jesseeichar** [comment]
Can you start a print and create a stack dump:

    sudo su tomcat
    jps -v
    jstack <pid> > /tmp/stackdump.txt

**Comment by sbrunner** [comment]
I try to reproduce it but without success, probably bad interaction with an other print version, I close it and reopen it if I found how to reproduce it...

**Comment by ochriste** [comment]
```
2015-09-29 14:37:19
Full thread dump OpenJDK 64-Bit Server VM (24.79-b02 mixed mode):

"Attach Listener" daemon prio=10 tid=0x00007f327c001000 nid=0x5a2e waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"localhost-startStop-1" daemon prio=10 tid=0x00007f3260004000 nid=0x591f runnable [0x00007f326b7af000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:272)
	at sun.security.provider.SeedGenerator$URLSeedGenerator.getSeedBytes(SeedGenerator.java:551)
	at sun.security.provider.SeedGenerator.generateSeed(SeedGenerator.java:139)
	at sun.security.provider.SecureRandom$SeederHolder.<clinit>(SecureRandom.java:197)
	at sun.security.provider.SecureRandom.engineNextBytes(SecureRandom.java:214)
	- locked <0x00000000fb0099b0> (a sun.security.provider.SecureRandom)
	at java.security.SecureRandom.nextBytes(SecureRandom.java:455)
	- locked <0x00000000fb00a248> (a java.security.SecureRandom)
	at java.security.SecureRandom.next(SecureRandom.java:477)
	at java.util.Random.nextInt(Random.java:239)
	at org.apache.catalina.util.SessionIdGeneratorBase.createSecureRandom(SessionIdGeneratorBase.java:234)
	at org.apache.catalina.util.SessionIdGeneratorBase.getRandomBytes(SessionIdGeneratorBase.java:171)
	at org.apache.catalina.util.StandardSessionIdGenerator.generateSessionId(StandardSessionIdGenerator.java:34)
	at org.apache.catalina.util.SessionIdGeneratorBase.generateSessionId(SessionIdGeneratorBase.java:164)
	at org.apache.catalina.session.ManagerBase.startInternal(ManagerBase.java:621)
	at org.apache.catalina.session.StandardManager.startInternal(StandardManager.java:456)
	- locked <0x00000000fabff048> (a org.apache.catalina.session.StandardManager)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	- locked <0x00000000fabff048> (a org.apache.catalina.session.StandardManager)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5238)
	- locked <0x00000000ff38d220> (a org.apache.catalina.core.StandardContext)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	- locked <0x00000000ff38d220> (a org.apache.catalina.core.StandardContext)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:919)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1703)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

"Catalina-startStop-1" daemon prio=10 tid=0x00007f32a04ce800 nid=0x591e waiting on condition [0x00007f326b8b1000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000ff3b2748> (a java.util.concurrent.FutureTask)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:425)
	at java.util.concurrent.FutureTask.get(FutureTask.java:187)
	at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:720)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:396)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1438)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:282)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402)
	- locked <0x00000000ff3646d0> (a org.apache.catalina.core.StandardHost)
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:347)
	- locked <0x00000000ff3646d0> (a org.apache.catalina.core.StandardHost)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:933)
	- locked <0x00000000ff3646d0> (a org.apache.catalina.core.StandardHost)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:868)
	- locked <0x00000000ff3646d0> (a org.apache.catalina.core.StandardHost)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	- locked <0x00000000ff3646d0> (a org.apache.catalina.core.StandardHost)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

"NioBlockingSelector.BlockPoller-2" daemon prio=10 tid=0x00007f32a04c4800 nid=0x591d runnable [0x00007f326b9b2000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	- locked <0x00000000ff38ff88> (a sun.nio.ch.Util$2)
	- locked <0x00000000ff38ff78> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000000ff38fe40> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	at org.apache.tomcat.util.net.NioBlockingSelector$BlockPoller.run(NioBlockingSelector.java:342)

"NioBlockingSelector.BlockPoller-1" daemon prio=10 tid=0x00007f32a0488800 nid=0x591c runnable [0x00007f326bab3000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	- locked <0x00000000ff3b2d98> (a sun.nio.ch.Util$2)
	- locked <0x00000000ff3b2d88> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000000ff3b2c70> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	at org.apache.tomcat.util.net.NioBlockingSelector$BlockPoller.run(NioBlockingSelector.java:342)

"GC Daemon" daemon prio=10 tid=0x00007f32a03ce000 nid=0x591b in Object.wait() [0x00007f32911d2000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000f0744d98> (a sun.misc.GC$LatencyLock)
	at sun.misc.GC$Daemon.run(GC.java:117)
	- locked <0x00000000f0744d98> (a sun.misc.GC$LatencyLock)

"Service Thread" daemon prio=10 tid=0x00007f32a00ab000 nid=0x58eb runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" daemon prio=10 tid=0x00007f32a00a9000 nid=0x58ea waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" daemon prio=10 tid=0x00007f32a00a6000 nid=0x58e9 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" daemon prio=10 tid=0x00007f32a00a3800 nid=0x58e8 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" daemon prio=10 tid=0x00007f32a0077800 nid=0x58e6 in Object.wait() [0x00007f32934f3000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000f0825518> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
	- locked <0x00000000f0825518> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" daemon prio=10 tid=0x00007f32a0075800 nid=0x58e5 in Object.wait() [0x00007f32935f4000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000f06991f0> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:503)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:133)
	- locked <0x00000000f06991f0> (a java.lang.ref.Reference$Lock)

"main" prio=10 tid=0x00007f32a000a800 nid=0x58d1 waiting on condition [0x00007f32a7d37000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000ff3b9870> (a java.util.concurrent.FutureTask)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:425)
	at java.util.concurrent.FutureTask.get(FutureTask.java:187)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916)
	- locked <0x00000000ff3b9de8> (a org.apache.catalina.core.StandardEngine)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	- locked <0x00000000ff3b9de8> (a org.apache.catalina.core.StandardEngine)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	- locked <0x00000000ff3b9de8> (a org.apache.catalina.core.StandardEngine)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:439)
	- locked <0x00000000ff3b9de8> (a org.apache.catalina.core.StandardEngine)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	- locked <0x00000000ff38e958> (a org.apache.catalina.core.StandardService)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:760)
	- locked <0x00000000f0be5500> (a java.lang.Object)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	- locked <0x00000000ff38eb10> (a org.apache.catalina.core.StandardServer)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:625)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:351)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:485)

"VM Thread" prio=10 tid=0x00007f32a0071000 nid=0x58e4 runnable 

"GC task thread#0 (ParallelGC)" prio=10 tid=0x00007f32a0020000 nid=0x58d8 runnable 

"GC task thread#1 (ParallelGC)" prio=10 tid=0x00007f32a0022000 nid=0x58d9 runnable 

"VM Periodic Task Thread" prio=10 tid=0x00007f32a00b5800 nid=0x58ec waiting on condition 

JNI global references: 169


```

**Comment by tsauerwein** [comment]
I did some research and found a possible problem. In `/var/log/tomcat/catalina.out` are a bunch of entries like the following:

    2015-10-21 11:19:55,772 [localhost-startStop-1] INFO  na.util.SessionIdGeneratorBase - Creation of 
    SecureRandom instance for session ID generation using [SHA1PRNG] took [479,740] milliseconds.

The creation of the session id generator sometimes takes several minutes. This can be avoided by using a non-blocking entropy source, see [Entropy Source](https://wiki.apache.org/tomcat/HowTo/FasterStartUp#Entropy_Source). This is less secure but should be no problem, because we are not using sessions for MFP.

So, could you please try to start Tomcat with `-Djava.security.egd=file:/dev/./urandom`?

*/srv/tomcat/tomcat1/bin/setenv-local.sh*:

    export ADD_JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom"

If this improves the situation, we should include this flag in the Puppet receipt (or update to Java 8 because this has improved in Java 8).

Also, the start-up time depends on the number of deployed apps. If you have 5 apps in `.../webapps` it will be 5-times slower. So when working on the print, it might make sense to remove webapps that are currently not needed.

**Comment by sbrunner** [comment]
Thanks for your investigation @tsauerwein we will try it :-)

**Comment by sbrunner** [comment]
Is there any reason to use the file `/dev/./urandom` instance of `/dev/urandom` ?

**Comment by tsauerwein** [comment]
See https://wiki.apache.org/tomcat/HowTo/FasterStartUp#Entropy_Source

>Note the "/./" characters in the value. They are needed to work around known Oracle JRE bug #6202721. See also JDK Enhancement Proposal 123. It is known that implementation of SecureRandom was improved in Java 8 onwards.

**Comment by sbrunner** [comment]
OK, thanks :-)

**Comment by pvalsecc** [comment]
I've improved the start time by disabling a few scannings performed by tomcat in the docker image. You can change the tomcat config that way: 4dab309f
