### ISSUE TITLE
problem with PNG export in V3 - javax.imageio.IIOException: Incompatible color conversion

### ISSUE THREAD

**Issue by ochriste** [mapfish/mapfish-print#340]
```
{"app":"morges","outputFormat":"png","layout":"1 A4 portrait","attributes":{"title":"","requestHeaders":{"requestHeaders":{"content-type":["application/json; charset=UTF-8"],"connection":["keep-alive"],"accept-language":["en-US,en;q=0.7,fr-CH;q=0.3"],"host":["morges-preprod.sig.cloud.camptocamp.net"],"accept":["text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"],"user-agent":["Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0"],"pragma":["no-cache"],"cache-control":["no-cache"],"cookie":["__utma=51683381.1766860717.1443781583.1448436044.1448441145.30; __utmz=51683381.1443781583.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utmc=51683381; auth_tkt_preprod=\"1a3084297b1cf49c5fc1ec00f6bf5efd4110b8e675983c7d223ea5b41805342ea448c6de0ee430b44a7d9f23889a3383153707455aa722629633abe1fb06dcc356544812YWRtaW4%3D!userid_type:b64unicode\"; auth_tkt_preprod=\"1a3084297b1cf49c5fc1ec00f6bf5efd4110b8e675983c7d223ea5b41805342ea448c6de0ee430b44a7d9f23889a3383153707455aa722629633abe1fb06dcc356544812YWRtaW4%3D!userid_type:b64unicode\"; auth_tkt_lgauthier=\"5a968887a46ad8ca8da5ff6c4dac5817a3e65a9089d20062f49df0af30edf942e69ef145561fe39efb3247d4378b0b36563e5282b998afb3f063f8af81a68c1e5654706bYWRtaW4%3D!userid_type:b64unicode\"; auth_tkt_lgauthier=\"5a968887a46ad8ca8da5ff6c4dac5817a3e65a9089d20062f49df0af30edf942e69ef145561fe39efb3247d4378b0b36563e5282b998afb3f063f8af81a68c1e5654706bYWRtaW4%3D!userid_type:b64unicode\"; __utmb=51683381.2.10.1448441145; __utmt=1"],"content-length":["275"],"accept-encoding":["gzip, deflate"],"referer":["http://morges-preprod.sig.cloud.camptocamp.net/lgauthier"],"x-requested-with":["XMLHttpRequest"]}},"legend":{"classes":[]},"map":{"center":[524467.47550723,153364.06222422],"scale":25000,"rotation":0,"layers":[],"projection":"EPSG:21781","dpi":254,"longitudeFirst":true},"datasource":[],"comments":""}}

net.sf.jasperreports.engine.JRRuntimeException: net.sf.jasperreports.engine.JRException: javax.imageio.IIOException: Incompatible color conversion
        at net.sf.jasperreports.engine.export.draw.PrintDrawVisitor.visit(PrintDrawVisitor.java:145) ~[PrintDrawVisitor.class:5.6.1]
        at net.sf.jasperreports.engine.export.draw.PrintDrawVisitor.visit(PrintDrawVisitor.java:59) ~[PrintDrawVisitor.class:5.6.1]
        at net.sf.jasperreports.engine.fill.JRTemplatePrintImage.accept(JRTemplatePrintImage.java:463) ~[JRTemplatePrintImage.class:5.6.1]
        at net.sf.jasperreports.engine.export.draw.FrameDrawer.draw(FrameDrawer.java:251) ~[FrameDrawer.class:5.6.1]
        at net.sf.jasperreports.engine.export.draw.FrameDrawer.draw(FrameDrawer.java:199) ~[FrameDrawer.class:5.6.1]
        at net.sf.jasperreports.engine.export.JRGraphics2DExporter.exportPage(JRGraphics2DExporter.java:338) ~[JRGraphics2DExporter.class:5.6.1]
        at net.sf.jasperreports.engine.export.JRGraphics2DExporter.exportReportToGraphics2D(JRGraphics2DExporter.java:311) ~[JRGraphics2DExporter.class:5.6.1]
        at net.sf.jasperreports.engine.export.JRGraphics2DExporter.exportReport(JRGraphics2DExporter.java:236) ~[JRGraphics2DExporter.class:5.6.1]
        at net.sf.jasperreports.engine.print.JRPrinterAWT.printPageToImage(JRPrinterAWT.java:282) ~[JRPrinterAWT.class:5.6.1]
        at net.sf.jasperreports.engine.JasperPrintManager.printToImage(JasperPrintManager.java:286) ~[JasperPrintManager.class:5.6.1]
        at org.mapfish.print.output.JasperReportImageOutputFormat.doExport(JasperReportImageOutputFormat.java:83) ~[JasperReportImageOutputFormat.class:na]
        at org.mapfish.print.output.AbstractJasperReportOutputFormat.print(AbstractJasperReportOutputFormat.java:115) ~[AbstractJasperReportOutputFormat.class:na]
        at org.mapfish.print.MapPrinter.print(MapPrinter.java:138) ~[MapPrinter.class:na]
        at org.mapfish.print.servlet.job.PrintJob$1.run(PrintJob.java:142) ~[PrintJob$1.class:na]
        at org.mapfish.print.servlet.job.FilePrintJob.withOpenOutputStream(FilePrintJob.java:50) ~[FilePrintJob.class:na]
        at org.mapfish.print.servlet.job.PrintJob.call(PrintJob.java:139) [PrintJob.class:na]
        at org.mapfish.print.servlet.job.PrintJob.call(PrintJob.java:56) [PrintJob.class:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_91]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_91]
Caused by: net.sf.jasperreports.engine.JRException: javax.imageio.IIOException: Incompatible color conversion
        at net.sf.jasperreports.engine.util.JRJdk14ImageReader.readImage(JRJdk14ImageReader.java:58) ~[JRJdk14ImageReader.class:5.6.1]
        at net.sf.jasperreports.engine.util.JRImageLoader.loadAwtImageFromBytes(JRImageLoader.java:167) ~[JRImageLoader.class:5.6.1]
        at net.sf.jasperreports.engine.JRImageRenderer.getImage(JRImageRenderer.java:418) ~[JRImageRenderer.class:5.6.1]
        at net.sf.jasperreports.engine.JRImageRenderer.getDimension(JRImageRenderer.java:493) ~[JRImageRenderer.class:5.6.1]
        at net.sf.jasperreports.engine.RenderableUtil.getOnErrorRendererForDimension(RenderableUtil.java:264) ~[RenderableUtil.class:5.6.1]
        at net.sf.jasperreports.engine.export.draw.ImageDrawer.draw(ImageDrawer.java:116) ~[ImageDrawer.class:5.6.1]
        at net.sf.jasperreports.engine.export.draw.PrintDrawVisitor.visit(PrintDrawVisitor.java:136) ~[PrintDrawVisitor.class:5.6.1]
        ... 20 common frames omitted
Caused by: javax.imageio.IIOException: Incompatible color conversion
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.checkColorConversion(JPEGImageReader.java:973) ~[na:1.7.0_91]
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1078) ~[na:1.7.0_91]
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1034) ~[na:1.7.0_91]
        at javax.imageio.ImageIO.read(ImageIO.java:1448) ~[na:1.7.0_91]
        at javax.imageio.ImageIO.read(ImageIO.java:1352) ~[na:1.7.0_91]
        at net.sf.jasperreports.engine.util.JRJdk14ImageReader.readImage(JRJdk14ImageReader.java:54) ~[JRJdk14ImageReader.class:5.6.1]
        ... 26 common frames omitted
```

**Comment by ochriste** [comment]
the problem was the color encoding of one of the jpeg included in the jasper report
![logo_morges_25_quadri](https://cloud.githubusercontent.com/assets/138678/11392804/5a0302d8-935c-11e5-8b58-ce8085dba064.jpg)
