### ISSUE TITLE
External graphics in point style does not seem to work

### ISSUE THREAD

**Issue by claustres** [mapfish/mapfish-print#493]
I am trying to print a geojson layer with a point style referencing an external graphics and get a null pointer exception. The layer also contains lines that print well. I have tested with MapFish v3.6 and v3.7, I am running tomcat 7.0.68 under Windows 7 64-bits. It does not work either with a file path relative to the configuration directory or with a URL like http://localhost:8080/print-servlet-3.7.0/site.png. The image file seems to be correctly found because if I set a bad URL I get another error (`Unable to read image at file://resources/site.png : Can't get input stream from URL!`). Any help is welcome, thanks in advance !

My layer object in the request is like this:
```json
{
  "geoJson": "file://resources/message-urgence-isovaleur-c1.json",
  "renderAsSvg": true,
  "style": {
      "*": {"symbolizers": [{
            "strokeColor": "#000000",
            "type": "line"
       }]},
       "[label = 'Site']": {"symbolizers": [{
             "externalGraphic": "site.png",
             "graphicWidth": 128,
             "graphicOpacity" : 1.0,
             "graphicFormat" : "image/png",
             "type": "point"
          }]},
          "version": "2"
       },
    "type": "geojson"
 }
```

Catalina output:
```
janv. 20, 2017 5:03:49 PM org.geotools.renderer.lite.StreamingRenderer fireErrorEvent
GRAVE: null
java.lang.NullPointerException
	at org.apache.batik.svggen.ImageHandlerBase64Encoder.encodeImage(ImageHandlerBase64Encoder.java:157)
	at org.apache.batik.svggen.ImageHandlerBase64Encoder.handleHREF(ImageHandlerBase64Encoder.java:133)
	at org.apache.batik.svggen.DefaultImageHandler.handleImage(DefaultImageHandler.java:91)
	at org.apache.batik.svggen.SimpleImageHandler.handleImage(SimpleImageHandler.java:126)
	at org.apache.batik.svggen.SVGGraphics2D.drawRenderedImage(SVGGraphics2D.java:1024)
	at org.geotools.renderer.lite.StyledShapePainter.renderImage(StyledShapePainter.java:614)
	at org.geotools.renderer.lite.StyledShapePainter.paint(StyledShapePainter.java:221)
	at org.geotools.renderer.lite.StreamingRenderer$PaintShapeRequest.execute(StreamingRenderer.java:3183)
	at org.geotools.renderer.lite.StreamingRenderer$PainterThread.run(StreamingRenderer.java:3503)
	at jsr166y.ForkJoinTask$AdaptedRunnable.exec(ForkJoinTask.java:1236)
	at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:305)
	at jsr166y.ForkJoinWorkerThread.execTask(ForkJoinWorkerThread.java:575)
	at jsr166y.ForkJoinPool.scan(ForkJoinPool.java:733)
	at jsr166y.ForkJoinPool.work(ForkJoinPool.java:617)
	at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:369)
```

**Comment by pvalsecc** [comment]
Fixed in https://github.com/mapfish/mapfish-print/commit/6a712209c54b1cb8cd2452790a3f81e5e4746612
