### ISSUE TITLE
Not possible to print a GeometryCollection

### ISSUE THREAD

**Issue by marionb** [mapfish/mapfish-print#604]
When trying to print a geojson that contains a GeometryCollection the following error appears:

      Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: geometries must not contain null elements

This error appeared on all versions 3.10.x as well as on master.

**Request JSON:**

    {
	"layout": "A4 portrait",
	"outputFormat": "pdf",
	"attributes": {
		"title": "Amtliche Vermessung Gde",
		"subtitle": "",
		"printScale": "1'000",
		"centerCoordinate": "2'739'011, 1'249'914",
		"epoch": "",
		"map": {
			"projection": "EPSG:2056",
			"dpi": 100,
			"rotation": 0,
			"center": [2739011, 1249914],
			"scale": 1000,
			"layers": [{
					"type": "geojson",
					"name": "search",
					"geoJson": {
						"type": "FeatureCollection",
						"features": [{
								"type": "Feature",
								"geometry": {
									"type": "GeometryCollection",
									"geometries": [{
											"type": "MultiLineString",
											"coordinates": [[[2739024.16384275, 1249955.99645933], [2739014.72195189, 1249952.38854164], [2739005.37306451, 1249947.71461492], [2738991.35021414, 1249945.37775968], [2738983.11429912, 1249944.70984995], [2738974.433389, 1249943.93094453], [2738963.27549946, 1249944.15907527]]]
										}, {
											"type": "MultiPoint",
											"coordinates": [[2738980.061, 1249914.028], [2739019.219, 1249917.041], [2739057.748, 1249913.638], [2739066.366, 1249930.744]]
										}
									]
								},
								"properties": {
									"type": "GeometryCollection"
								}
							},{
								"type": "Feature",
								"geometry": {
									"type": "MultiPoint",
									"coordinates": [[2738980.061, 1249914.028], [2739019.219, 1249917.041], [2739057.748, 1249913.638], [2739066.366, 1249930.744]]
								},
								"properties": {
									"type": "MultiPoint"
								}
							}
						]
					},
					"renderAsSvg": false,
					"style": {
						"version": "2",
						"[type = 'MultiLineString']": {
							"symbolizers": [{
									"type": "line",
									"strokeLinecap": "butt",
									"strokeColor": "rgb(10, 130, 210)",
									"strokeWidth": 2
								}
							]
						},
						"[type = 'MultiPolygon']": {
							"symbolizers": [{
									"type": "line",
									"strokeLinecap": "butt",
									"strokeColor": "rgb(10, 130, 210)",
									"strokeWidth": 2
								}, {
									"type": "polygon",
									"strokeLinecap": "butt",
									"strokeWidth": 1,
									"fillOpacity": 0,
									"strokeColor": "rgb(10, 130, 210)"
								}
							]
						},
						"[type = 'Polygon']": {
							"symbolizers": [{
									"type": "line",
									"strokeLinecap": "butt",
									"strokeColor": "rgb(10, 130, 210)",
									"strokeWidth": 2
								}, {
									"type": "polygon",
									"strokeLinecap": "butt",
									"strokeWidth": 1,
									"fillOpacity": 0,
									"strokeColor": "rgb(10, 130, 210)"
								}
							]
						},
						"[type = 'Point']": {
							"symbolizers": [{
									"type": "point",
									"graphicName": "circle",
									"strokeColor": "rgb(10, 130, 210)",
									"strokeWidth": 1,
									"graphicOpacity": 0,
									"pointRadius": 3,
									"fillColor": "rgb(10, 130, 210)"
								}
							]
						},
						"[type = 'MultiPoint']": {
							"symbolizers": [{
									"type": "point",
									"graphicName": "circle",
									"strokeColor": "rgb(10, 180, 20)",
									"strokeWidth": 1,
									"graphicOpacity": 0,
									"pointRadius": 3,
									"fillColor": "rgb(0, 255, 0)"
								}
							]
						},
						"[type = 'GeometryCollection']": {
							"symbolizers": [{
									"type": "point",
									"graphicName": "circle",
									"strokeColor": "rgb(255, 0, 0)",
									"strokeWidth": 1,
									"graphicOpacity": 0,
									"pointRadius": 3,
									"fillColor": "rgb(255, 0, 0)"
								}, {
									"type": "line",
									"strokeLinecap": "butt",
									"strokeColor": "rgb(10, 10, 210)",
									"strokeWidth": 2
								}
							]
						}
					}
				}
			]
		}
	}}

**The full stack trace can be seen bellow:**

    Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: geometries must not contain null elements
    	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
    	at org.mapfish.print.output.AbstractJasperReportOutputFormat.getJasperPrint(AbstractJasperReportOutputFormat.java:146)
    	at org.mapfish.print.output.AbstractJasperReportOutputFormat.print(AbstractJasperReportOutputFormat.java:94)
    	at org.mapfish.print.MapPrinter.print(MapPrinter.java:126)
    	at org.mapfish.print.cli.Main.run(Main.java:163)
    	at org.mapfish.print.cli.Main.runMain(Main.java:119)
    	at org.mapfish.print.cli.Main.main(Main.java:73)
    Caused by: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: geometries must not contain null elements
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
    	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
    	... 6 more
    Caused by: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: geometries must not contain null elements
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
    	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
    	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
    	at org.mapfish.print.processor.ProcessorDependencyGraph$ProcessorGraphForkJoinTask.compute(ProcessorDependencyGraph.java:185)
    	at org.mapfish.print.processor.ProcessorDependencyGraph$ProcessorGraphForkJoinTask.compute(ProcessorDependencyGraph.java:140)
    	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
    	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
    Caused by: java.lang.IllegalArgumentException: geometries must not contain null elements
    	at com.vividsolutions.jts.geom.GeometryCollection.<init>(GeometryCollection.java:76)
    	at com.vividsolutions.jts.geom.GeometryFactory.createGeometryCollection(GeometryFactory.java:303)
    	at org.geotools.geojson.geom.GeometryCollectionHandler.endObject(GeometryCollectionHandler.java:64)
    	at org.geotools.geojson.DelegatingHandler.endObject(DelegatingHandler.java:81)
    	at org.geotools.geojson.feature.FeatureHandler.endObject(FeatureHandler.java:136)
    	at org.geotools.geojson.DelegatingHandler.endObject(DelegatingHandler.java:81)
    	at org.geotools.geojson.feature.FeatureCollectionHandler.endObject(FeatureCollectionHandler.java:121)
    	at org.json.simple.parser.JSONParser.parse(Unknown Source)
    	at org.geotools.geojson.feature.FeatureJSON$FeatureCollectionIterator.readNext(FeatureJSON.java:746)
    	at org.geotools.geojson.feature.FeatureJSON$FeatureCollectionIterator.hasNext(FeatureJSON.java:734)
    	at org.geotools.geojson.feature.FeatureJSON.readFeatureCollection(FeatureJSON.java:362)
    	at org.geotools.geojson.feature.FeatureJSON.readFeatureCollection(FeatureJSON.java:395)
    	at org.mapfish.print.map.geotools.FeaturesParser.readFeatureCollection(FeaturesParser.java:146)
    	at org.mapfish.print.map.geotools.FeaturesParser.treatStringAsGeoJson(FeaturesParser.java:133)
    	at org.mapfish.print.map.geotools.FeaturesParser.autoTreat(FeaturesParser.java:82)
    	at org.mapfish.print.map.geotools.GeoJsonLayer$Plugin$1.load(GeoJsonLayer.java:89)
    	at org.mapfish.print.map.geotools.AbstractFeatureSourceLayer.getFeatureSource(AbstractFeatureSourceLayer.java:66)
    	at org.mapfish.print.map.geotools.AbstractFeatureSourceLayer.getLayers(AbstractFeatureSourceLayer.java:75)
    	at org.mapfish.print.map.geotools.AbstractGeotoolsLayer.render(AbstractGeotoolsLayer.java:76)
    	at org.mapfish.print.processor.map.CreateMapProcessor.createLayerGraphics(CreateMapProcessor.java:336)
    	at org.mapfish.print.processor.map.CreateMapProcessor.execute(CreateMapProcessor.java:135)
    	at org.mapfish.print.processor.map.CreateMapProcessor.execute(CreateMapProcessor.java:103)
    	at org.mapfish.print.processor.ProcessorGraphNode$ProcessorNodeForkJoinTask.compute(ProcessorGraphNode.java:202)
    	at org.mapfish.print.processor.ProcessorGraphNode$ProcessorNodeForkJoinTask.compute(ProcessorGraphNode.java:177)
    	... 5 more

**Comment by pvalsecc** [comment]
Must be related to https://osgeo-org.atlassian.net/browse/GEOT-5687
I've tried to upgrade to GT 17.3 and the fix is not there. With GT 18, the print fails with a "call to virtual method" error in Jasper for some reason...

**Comment by pvalsecc** [comment]
@marionb, please test with MFP 3.11.1. It should fix this bug. Warning: java >=1.8.0

**Comment by marionb** [comment]
All the errors are gone and I a result So this issue is fixed for me. Thanks!
However the result for Multipont within a geometry collection is not correct. They get printed different/wrong with respect to if they are not in a geometry collection. I will open a new issue for this to keep thins separated.
