### ISSUE TITLE
Application crashes if proxy configuration contains an inexisting dnsmatch

### ISSUE THREAD

**Issue by svareg** [mapfish/mapfish-print#773]
Hello,

I've configured a proxy in my config.yaml file:

```
proxies:
    - !proxy
      scheme: http
      host: xxxxx
      port: 0000
      username: xxxxx
      password: xxxxx
      matchers:
        - !localMatch
          reject: true

        - !dnsMatch
          host: bdpc7246842
          reject: true
(...)
```

If bdpc7246842 does not exists, MapFish throw an exception, and won't generate my report:

```
Dec 10 09:05:53 bvdgdi-svdprt1 docker-tomcat[99791]: org.yaml.snakeyaml.constructor.ConstructorException: Cannot create property=proxies for JavaBean=org.mapfish.print.config.Configuration@59c7f60e; Cannot create property=matchers for JavaBean=org.mapfish.print.http.HttpProxy@73ba1184; Cannot create property=host for JavaBean=DnsHostMatcher{host='bdpc7246842', reject=false}; null;  in 'reader', line 35, column 17:
Dec 10 09:05:53 bvdgdi-svdprt1 docker-tomcat[99791]:               host: bdpc7246842
Dec 10 09:05:53 bvdgdi-svdprt1 docker-tomcat[99791]:                     ^;  in 'reader', line 13, column 9:
Dec 10 09:05:53 bvdgdi-svdprt1 docker-tomcat[99791]:             - !localMatch
Dec 10 09:05:53 bvdgdi-svdprt1 docker-tomcat[99791]:             ^;  in 'reader', line 6, column 5:
Dec 10 09:05:53 bvdgdi-svdprt1 docker-tomcat[99791]:         - !proxy
Dec 10 09:05:53 bvdgdi-svdprt1 docker-tomcat[99791]:         ^
```

Can't it just ignore it, if this host is (temporary) not found ?
What do you think ?
Thanks !

**Comment by pvalsecc** [comment]
I'd say it's a feature, not a bug. Those matchers are moslty used for securing the features.

**Comment by svareg** [comment]
It happend because some machine names have changed, and they were configured in the file _config.yaml_ as proxy exceptions.

I don't actually need any correction, but that's a somehow confusing for a _"feature"_...
For a right feature I would expect at least a correct error message, not a crash.

**Comment by svareg** [comment]
Unfortunately, it seems that _!hostnameMatch_ does work in proxies configuration :

```
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
Dec 11 15:02:53 bvdgdi-svdprt1 docker-tomcat[36412]:         at java.lang.Thread.run(Thread.java:748)
Dec 11 15:02:53 bvdgdi-svdprt1 docker-tomcat[36412]: Caused by: org.yaml.snakeyaml.constructor.ConstructorException: Cannot create property=matchers for JavaBean=org.mapfish.print.http.HttpProxy@2852dfd; null; Can't construct a java object for !hostnameMatch; exception=Invalid tag: !hostnameMatch;  in 'reader', line 42, column 11:
Dec 11 15:02:53 bvdgdi-svdprt1 docker-tomcat[36412]:             - !hostnameMatch
Dec 11 15:02:53 bvdgdi-svdprt1 docker-tomcat[36412]:               ^;  in 'reader', line 13, column 9:
```

I'm using version 3.10.7.

But that's not very important, I know I must change the name manually when this case occurs.
I was posting here in case you identify this as a bug.

Thanks for your quick answer.

**Comment by pvalsecc** [comment]
This matcher has been introduced in 3.12.0

**Comment by svareg** [comment]
Hello,

Ok, I'll see if we could migrate.

Thanks !
