### ISSUE TITLE
first call to mapfish-print is not fully functional

### ISSUE THREAD

**Issue by jwkaltz** [mapfish/mapfish-print#819]
The project pyramid_oereb uses mapfish-print for generating PDFs. In our project instances, mapfish-print is typically running within Tomcat. In this context of usage, the first call to mapfish-print after a Tomcat restart is not fully functional:
- if running mapfish-print 3.10.7, the first call often results in a NullPointerException. All subsequent calls work fine.
- if running mapfish-print 3.18 and using Mozilla Firefox, the first call usually results in the error "Error while processing request:
java.net.SocketException: Network is unreachable (connect failed)". All subsequent calls work fine 
- if running mapfish-print 3.18 and using Google Chrome, the first call usually results in a PDF where some images (maps) are empty. In all subsequent calls, the PDF contains all maps correctly.

How to reproduce in a local setup:
- get project https://github.com/openoereb/pyramid_oereb
- change the file "print/Docker" to try different version of mapfish-print
- do a "make serve"
- Open in a browser http://localhost:6543/oereb/extract/reduced/pdf/CH113928077734

Note that experiences when using this setup on server instances vary. One user reports that the PDF generation does work even on the first call, but only if waiting for about 20 minutes before making the first call.

See https://github.com/openoereb/pyramid_oereb/issues/239 for the issue description within the pyramid_oereb

**Comment by pvalsecc** [comment]
Thanks for the very complete bug report!
I'd add that to reproduce for sure, the machine running the print must have the CPU busy doing other stuff while the first print job is running.

**Comment by pvalsecc** [comment]
Looks like there is another bug with the temporary file creation:
```
java.io.IOException: No such file or directory
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.io.File.createTempFile(File.java:2024)
        at org.mapfish.print.http.HttpRequestFetcher$CachedClientHttpResponse.<init>(HttpRequestFetcher.java:91)
        at org.mapfish.print.http.HttpRequestFetcher$CachedClientHttpResponse.<init>(HttpRequestFetcher.java:78)
        at org.mapfish.print.http.HttpRequestFetcher$CachedClientHttpRequest.lambda$call$0(HttpRequestFetcher.java:199)
        at org.mapfish.print.processor.AbstractProcessor$Context.mdcContextEx(AbstractProcessor.java:261)
        at org.mapfish.print.http.HttpRequestFetcher$CachedClientHttpRequest.call(HttpRequestFetcher.java:193)
        at org.mapfish.print.http.HttpRequestFetcher$CachedClientHttpRequest.call(HttpRequestFetcher.java:132)
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by pvalsecc** [comment]
OK, the IOException was due to a network error.
