### ISSUE TITLE
Error printing legends: Illegal output type!

### ISSUE THREAD

**Issue by vfonsecaz** [mapfish/mapfish-print#861]
Mapfish sometimes fails on the legend section (making the request without the GetLegendGraphic url works)

```json
		"legend": {
			"name": "",
			"classes": [{
				"icons": ["http://geoserver/wms?VERSION=1.3.0&REQUEST=GetLegendGraphic&LAYER=<layer>&LEGEND_OPTIONS=fontSize:20;labelMargin:10&FORMAT=image/png&WIDTH=30&HEIGHT=30"],
				"name": "Name"
			},...]
		}
```

The legend url works fine if i open in a browser window. 
**If I restart the tomcat instance everything goes back to normal**

This is the error log:
```
java.lang.IllegalArgumentException: Illegal output type!
	at javax.imageio.ImageWriter.setOutput(ImageWriter.java:219)
	at it.geosolutions.imageio.plugins.turbojpeg.TurboJpegImageWriter.setOutput(TurboJpegImageWriter.java:130)
	at javax.imageio.ImageIO.doWrite(ImageIO.java:1610)
	at javax.imageio.ImageIO.write(ImageIO.java:1578)
	at net.sf.jasperreports.engine.util.JRJdk14ImageEncoder.encode(JRJdk14ImageEncoder.java:79)
	at net.sf.jasperreports.engine.util.JRAbstractImageEncoder.encode(JRAbstractImageEncoder.java:73)
	at net.sf.jasperreports.engine.util.JRImageLoader.loadBytesFromAwtImage(JRImageLoader.java:152)
	at net.sf.jasperreports.renderers.util.RendererUtil.getRenderable(RendererUtil.java:223)
	at net.sf.jasperreports.renderers.util.RendererUtil.getRenderable(RendererUtil.java:205)
	at net.sf.jasperreports.engine.fill.JRFillImage.evaluateImage(JRFillImage.java:560)
	at net.sf.jasperreports.engine.fill.JRFillImage.evaluate(JRFillImage.java:485)
	at net.sf.jasperreports.engine.fill.JRFillElementContainer.evaluate(JRFillElementContainer.java:383)
	at net.sf.jasperreports.engine.fill.JRFillBand.evaluate(JRFillBand.java:533)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillColumnBand(JRVerticalFiller.java:2549)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillDetail(JRVerticalFiller.java:791)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReportContent(JRVerticalFiller.java:272)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReport(JRVerticalFiller.java:103)
	at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:609)
	at net.sf.jasperreports.engine.fill.BaseReportFiller.fill(BaseReportFiller.java:405)
	at net.sf.jasperreports.engine.fill.JRFillSubreport.fillSubreport(JRFillSubreport.java:740)
	at net.sf.jasperreports.engine.fill.JRSubreportRunnable.run(JRSubreportRunnable.java:59)
	at net.sf.jasperreports.engine.fill.AbstractThreadSubreportRunner.run(AbstractThreadSubreportRunner.java:221)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
gradle: 11:54:01.858 [http-bio-8989-exec-118] ERROR o.m.print.servlet.BaseMapServlet - Error while processing request: java.lang.IllegalArgumentException: Illegal output type!
```

So I really don't know it it's geoserver or mapfish related.

**Comment by pvalsecc** [comment]
What version of the print, have you tried the latest?

**Comment by vfonsecaz** [comment]
yes sorry.
mfp 3.17.0

I can try the latest. Bu the difficult part is reproducing the problem, because i don't know the circumstances which lead to the error.

**Comment by pvalsecc** [comment]
My guess: WMS is a crappy protocol and uses status=200 in case of error, but puts some XML in the body instead of an image. Jasper thinks the image is fine, tries to read that as an image and goes boom.

If I were you, I'd check the geoserver logs around the time the error occurred in MFP.

**Comment by vfonsecaz** [comment]
I've updated to 3.18.4
I will debug and post back if i find anything useful.

thanks

**Comment by vfonsecaz** [comment]
Unfortunately the problem persists! Same error, same log!

mfp 3.18.4

**Comment by pvalsecc** [comment]
If I were you, I'd check the geoserver logs around the time the error occurred in MFP.

**Comment by vfonsecaz** [comment]
Only found this relevant information in geoserver logs

`2019-03-12 14:19:24,368 DEBUG [wms.map] - Writing png image ...
2019-03-12 14:19:24,369 DEBUG [geotools.styling] - number of fts set 1
2019-03-12 14:19:24,369 DEBUG [geoserver.filters] - Not compressing output for mimetype: image/png
2019-03-12 14:19:24,479 DEBUG [wms.map] - Writing png image ... done!
`

**Comment by pvalsecc** [comment]
Yeah, not very helpful...

**Comment by vfonsecaz** [comment]
I think i'll use geoserver cached wms legends for now (legendsamples folder in gs data directory)

**Comment by vfonsecaz** [comment]
I ended up using a table processor insted of the legend processor

requestData.json

`
...
"table": {
			"columns": ["id", "Legend", "Layer"],
			"data": [
				["1", "http://geoserver/wms?REQUEST=GetLegendGraphic&EXCEPTIONS=application/vnd.ogc.se_xml&LAYER=layer1&FORMAT=image/png&WIDTH=30", "Layer 1"],
				["1", "http://geoserver/wms?REQUEST=GetLegendGraphic&EXCEPTIONS=application/vnd.ogc.se_xml&LAYER=layer2&FORMAT=image/png&WIDTH=30", "Layer 2"],
				["1", "http://geoserver/wms?REQUEST=GetLegendGraphic&EXCEPTIONS=application/vnd.ogc.se_xml&LAYER=layer3&FORMAT=image/png&WIDTH=30", "Layer 3"]
			]
		}
...`

config.waml

`
    attributes:
...
      table: !table {}
...
    processors:
    - !prepareTable {}     
...
`

The getlegendgraphic url is the same as it was in the legendprocessor but it's working now!

**Comment by pvalsecc** [comment]
OK, thanks for the workaround.
